### ISSUE TITLE
JSON serialization error?

### ISSUE THREAD

**Issue by vals** [chanzuckerberg/cellxgene#1125]
Hi,

I'm looking into using `cellxgene`, but something is not working on the example data? Am I missing something?

I couldn't find any other issues discussing this. I installed miniconda and then `cellxgene`, running version `0.13.0`. Here is the on-server error message:

```
(base) ubuntu@ip-10-60-220-209:~$ cellxgene launch --disable-diffexp --host 10.60.220.209 --port 8888 -v https://cellxgene-example-data.czi.technology/pbmc3k.h5ad
[cellxgene] Starting the CLI...
[cellxgene] Loading data from pbmc3k.h5ad.
[cellxgene] Warning: Annotation log1p_n_genes_by_counts will be converted to 32 bit float and may lose precision.
[cellxgene] Warning: Annotation pct_counts_in_top_50_genes will be converted to 32 bit float and may lose precision.
[cellxgene] Warning: Annotation pct_counts_in_top_100_genes will be converted to 32 bit float and may lose precision.
[cellxgene] Warning: Annotation pct_counts_in_top_200_genes will be converted to 32 bit float and may lose precision.
[cellxgene] Warning: Annotation pct_counts_in_top_500_genes will be converted to 32 bit float and may lose precision.
[cellxgene] Warning: Annotation pct_dropout_by_counts will be converted to 32 bit float and may lose precision.
[cellxgene] Launching! Please go to http://10.60.220.209:8888 in your browser.
[cellxgene] Type CTRL-C at any time to exit.
 * Serving Flask app "server.app.app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://10.60.220.209:8888/ (Press CTRL+C to quit)
10.60.20.246 - - [24/Jan/2020 15:32:35] "GET / HTTP/1.1" 200 -
10.60.20.246 - - [24/Jan/2020 15:32:36] "GET /api/v0.2/schema HTTP/1.1" 200 -
[2020-01-24 15:32:36,156] ERROR in app: Exception on /api/v0.2/config [GET]
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/server/app/rest_api/rest.py", line 81, in get
    return make_response(jsonify(config), HTTPStatus.OK)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/ubuntu/miniconda3/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/ubuntu/miniconda3/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/server/app/util/utils.py", line 26, in default
    return json.JSONEncoder.default(self, obj)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/home/ubuntu/miniconda3/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Version is not JSON serializable
10.60.20.246 - - [24/Jan/2020 15:32:36] "GET /api/v0.2/config HTTP/1.1" 500 -
10.60.20.246 - - [24/Jan/2020 15:32:36] "GET /favicon.png HTTP/1.1" 200 -
```

**Comment by bkmartinjr** [comment]
I am guessing this is a new installation - you installed cellxgene within the last two days?   Please confirm.

If above assumption is true, this is caused the most recent AnnData release - cellxgene is incompatible with it (we are working on a fix). 

In the meantime, a workaround is to install the previous version of anndata.
```
% pip install anndata==0.6.22post1
```

If you installed cellxgene in a virtual environment, make sure do the above while that virtual environment is active.

**Comment by vals** [comment]
Yes this is true, I created a new server for this on AWS and just installed miniconda and `cellxgene` yesterday.

Thank you! I didn't realize there was a new version of AnnData released, I'll look into it.
