### ISSUE TITLE
CLI should print better error messages for inaccessible files

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1270]
If you specify a bad file name, you get a stack trace.  Should print a nice error.

```
# cellxgene launch example-dataset/pbmc3k.h5adj
[cellxgene] Starting the CLI...
Traceback (most recent call last):
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/bin/cellxgene", line 11, in <module>
    load_entry_point('cellxgene', 'console_scripts', 'cellxgene')()
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/mnt/c/Users/bruce/projects/cellxgene/server/cli/launch.py", line 69, in wrapper
    return func(*args, **kwargs)
  File "/mnt/c/Users/bruce/projects/cellxgene/server/cli/launch.py", line 116, in wrapper
    return func(*args, **kwargs)
  File "/mnt/c/Users/bruce/projects/cellxgene/server/cli/launch.py", line 152, in wrapper
    return func(*args, **kwargs)
  File "/mnt/c/Users/bruce/projects/cellxgene/server/cli/launch.py", line 202, in wrapper
    return func(*args, **kwargs)
  File "/mnt/c/Users/bruce/projects/cellxgene/server/cli/launch.py", line 233, in wrapper
    return func(*args, **kwargs)
  File "/mnt/c/Users/bruce/projects/cellxgene/server/cli/launch.py", line 322, in launch
    matrix_data_loader = MatrixDataLoader(datapath)
  File "/mnt/c/Users/bruce/projects/cellxgene/server/data_common/matrix_loader.py", line 151, in __init__
    raise DatasetAccessError(
server.common.errors.DatasetAccessError: <server.common.data_locator.DataLocator object at 0x7f8ec3791b20> does not have an allowed type: MatrixDataType.UNKNOWN
```

**Comment by bmccandless** [comment]
This has been fixed:
```
[cellxgene] Starting the CLI...
Error: Dataset does not exist.
```
