### ISSUE TITLE
CLI install script failed on Win10/WSL/Ubuntu - could not find HDF5 libs

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#140]
I followed the instructions in the README to install the local CLI.  It failed with:

```
/usr/bin/ld: cannot find -lhdf5
collect2: error: ld returned 1 exit status
.. ERROR:: Could not find a local HDF5 installation.
   You may need to explicitly state where your local HDF5 headers and
   library can be found by setting the ``HDF5_DIR`` environment
   variable or by using the ``--hdf5`` command-line option.
error: Setup script exited with 1
```

Config:
* Py 3.5.2
* Win10, WSL (Ubuntu 16)

full details

```
(cellxgene) root@woof:/mnt/c/Users/bruce/projects/cellxgene# python3 setup.py install
running install
running bdist_egg
running egg_info
creating cellxgene.egg-info
writing cellxgene.egg-info/PKG-INFO
writing requirements to cellxgene.egg-info/requires.txt
writing entry points to cellxgene.egg-info/entry_points.txt
writing top-level names to cellxgene.egg-info/top_level.txt
writing dependency_links to cellxgene.egg-info/dependency_links.txt
writing manifest file 'cellxgene.egg-info/SOURCES.txt'
reading manifest file 'cellxgene.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'cellxgene.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/lib
creating build/lib/server
copying server/run.py -> build/lib/server
copying server/__init__.py -> build/lib/server
creating build/lib/server/app
copying server/app/app.py -> build/lib/server/app
copying server/app/__init__.py -> build/lib/server/app
creating build/lib/server/app/driver
copying server/app/driver/driver.py -> build/lib/server/app/driver
copying server/app/driver/__init__.py -> build/lib/server/app/driver
creating build/lib/server/app/rest_api
copying server/app/rest_api/rest.py -> build/lib/server/app/rest_api
copying server/app/rest_api/__init__.py -> build/lib/server/app/rest_api
creating build/lib/server/app/scanpy_engine
copying server/app/scanpy_engine/scanpy_engine.py -> build/lib/server/app/scanpy_engine
copying server/app/scanpy_engine/__init__.py -> build/lib/server/app/scanpy_engine
creating build/lib/server/app/util
copying server/app/util/filter.py -> build/lib/server/app/util
copying server/app/util/schema_parse.py -> build/lib/server/app/util
copying server/app/util/utils.py -> build/lib/server/app/util
copying server/app/util/__init__.py -> build/lib/server/app/util
creating build/lib/server/app/web
copying server/app/web/webapp.py -> build/lib/server/app/web
copying server/app/web/__init__.py -> build/lib/server/app/web
creating build/lib/server/app/web/static
creating build/lib/server/app/web/static/css
copying server/app/web/static/css/main.910b75bc.css -> build/lib/server/app/web/static/css
copying server/app/web/static/css/main.910b75bc.css.map -> build/lib/server/app/web/static/css
creating build/lib/server/app/web/static/img
copying server/app/web/static/img/favicon.png -> build/lib/server/app/web/static/img
creating build/lib/server/app/web/static/js
copying server/app/web/static/js/main.57a9e9cb.js -> build/lib/server/app/web/static/js
copying server/app/web/static/js/main.57a9e9cb.js.map -> build/lib/server/app/web/static/js
copying server/app/web/static/js/service-worker.js -> build/lib/server/app/web/static/js
creating build/lib/server/app/web/templates
copying server/app/web/templates/index.html -> build/lib/server/app/web/templates
copying server/app/web/templates/swagger.html -> build/lib/server/app/web/templates
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/server
creating build/bdist.linux-x86_64/egg/server/app
copying build/lib/server/app/app.py -> build/bdist.linux-x86_64/egg/server/app
creating build/bdist.linux-x86_64/egg/server/app/driver
copying build/lib/server/app/driver/driver.py -> build/bdist.linux-x86_64/egg/server/app/driver
copying build/lib/server/app/driver/__init__.py -> build/bdist.linux-x86_64/egg/server/app/driver
creating build/bdist.linux-x86_64/egg/server/app/rest_api
copying build/lib/server/app/rest_api/rest.py -> build/bdist.linux-x86_64/egg/server/app/rest_api
copying build/lib/server/app/rest_api/__init__.py -> build/bdist.linux-x86_64/egg/server/app/rest_api
creating build/bdist.linux-x86_64/egg/server/app/scanpy_engine
copying build/lib/server/app/scanpy_engine/scanpy_engine.py -> build/bdist.linux-x86_64/egg/server/app/scanpy_engine
copying build/lib/server/app/scanpy_engine/__init__.py -> build/bdist.linux-x86_64/egg/server/app/scanpy_engine
creating build/bdist.linux-x86_64/egg/server/app/util
copying build/lib/server/app/util/filter.py -> build/bdist.linux-x86_64/egg/server/app/util
copying build/lib/server/app/util/schema_parse.py -> build/bdist.linux-x86_64/egg/server/app/util
copying build/lib/server/app/util/utils.py -> build/bdist.linux-x86_64/egg/server/app/util
copying build/lib/server/app/util/__init__.py -> build/bdist.linux-x86_64/egg/server/app/util
creating build/bdist.linux-x86_64/egg/server/app/web
creating build/bdist.linux-x86_64/egg/server/app/web/static
creating build/bdist.linux-x86_64/egg/server/app/web/static/css
copying build/lib/server/app/web/static/css/main.910b75bc.css -> build/bdist.linux-x86_64/egg/server/app/web/static/css
copying build/lib/server/app/web/static/css/main.910b75bc.css.map -> build/bdist.linux-x86_64/egg/server/app/web/static/css
creating build/bdist.linux-x86_64/egg/server/app/web/static/img
copying build/lib/server/app/web/static/img/favicon.png -> build/bdist.linux-x86_64/egg/server/app/web/static/img
creating build/bdist.linux-x86_64/egg/server/app/web/static/js
copying build/lib/server/app/web/static/js/main.57a9e9cb.js -> build/bdist.linux-x86_64/egg/server/app/web/static/js
copying build/lib/server/app/web/static/js/main.57a9e9cb.js.map -> build/bdist.linux-x86_64/egg/server/app/web/static/js
copying build/lib/server/app/web/static/js/service-worker.js -> build/bdist.linux-x86_64/egg/server/app/web/static/js
creating build/bdist.linux-x86_64/egg/server/app/web/templates
copying build/lib/server/app/web/templates/index.html -> build/bdist.linux-x86_64/egg/server/app/web/templates
copying build/lib/server/app/web/templates/swagger.html -> build/bdist.linux-x86_64/egg/server/app/web/templates
copying build/lib/server/app/web/webapp.py -> build/bdist.linux-x86_64/egg/server/app/web
copying build/lib/server/app/web/__init__.py -> build/bdist.linux-x86_64/egg/server/app/web
copying build/lib/server/app/__init__.py -> build/bdist.linux-x86_64/egg/server/app
copying build/lib/server/run.py -> build/bdist.linux-x86_64/egg/server
copying build/lib/server/__init__.py -> build/bdist.linux-x86_64/egg/server
byte-compiling build/bdist.linux-x86_64/egg/server/app/app.py to app.cpython-35.pyc
  File "build/bdist.linux-x86_64/egg/server/app/app.py", line 11
    REACTIVE_LIMIT = 1_000_000
                             ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/server/app/driver/driver.py to driver.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/server/app/driver/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/server/app/rest_api/rest.py to rest.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/server/app/rest_api/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/server/app/scanpy_engine/scanpy_engine.py to scanpy_engine.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/server/app/scanpy_engine/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/server/app/util/filter.py to filter.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/server/app/util/schema_parse.py to schema_parse.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/server/app/util/utils.py to utils.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/server/app/util/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/server/app/web/webapp.py to webapp.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/server/app/web/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/server/app/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/server/run.py to run.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/server/__init__.py to __init__.cpython-35.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying cellxgene.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cellxgene.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cellxgene.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cellxgene.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cellxgene.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cellxgene.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cellxgene.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/cellxgene-0.0.1-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing cellxgene-0.0.1-py3.5.egg
creating /mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.5/site-packages/cellxgene-0.0.1-py3.5.egg
Extracting cellxgene-0.0.1-py3.5.egg to /mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.5/site-packages
  File "/mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.5/site-packages/cellxgene-0.0.1-py3.5.egg/server/app/app.py", line 11
    REACTIVE_LIMIT = 1_000_000
                             ^
SyntaxError: invalid syntax

Adding cellxgene 0.0.1 to easy-install.pth file
Installing cellxgene script to /mnt/c/Users/bruce/projects/cellxgene/cellxgene/bin

Installed /mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.5/site-packages/cellxgene-0.0.1-py3.5.egg
Processing dependencies for cellxgene==0.0.1
Searching for Werkzeug==0.14.1
Reading https://pypi.python.org/simple/Werkzeug/
Best match: Werkzeug 0.14.1
Downloading https://files.pythonhosted.org/packages/9f/08/a3bb1c045ec602dc680906fc0261c267bed6b3bb4609430aff92c3888ec8/Werkzeug-0.14.1.tar.gz#sha256=c3fd7a7d41976d9f44db327260e263132466836cef6f91512889ed60ad26557c
Processing Werkzeug-0.14.1.tar.gz
Writing /tmp/easy_install-ajmb636f/Werkzeug-0.14.1/setup.cfg
Running Werkzeug-0.14.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ajmb636f/Werkzeug-0.14.1/egg-dist-tmp-0in72ea8
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/_themes'
warning: no previously-included files matching '*.py[cdo]' found anywhere in distribution
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
creating /mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.5/site-packages/Werkzeug-0.14.1-py3.5.egg
Extracting Werkzeug-0.14.1-py3.5.egg to /mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.5/site-packages
Adding Werkzeug 0.14.1 to easy-install.pth file

Installed /mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.5/site-packages/Werkzeug-0.14.1-py3.5.egg
Searching for urllib3==1.23
Reading https://pypi.python.org/simple/urllib3/
Best match: urllib3 1.23
Downloading https://files.pythonhosted.org/packages/3c/d2/dc5471622bd200db1cd9319e02e71bc655e9ea27b8e0ce65fc69de0dac15/urllib3-1.23.tar.gz#sha256=a68ac5e15e76e7e5dd2b8f94007233e01effe3e50e8daddf69acfd81cb686baf
Processing urllib3-1.23.tar.gz
Writing /tmp/easy_install-u9zkz5sn/urllib3-1.23/setup.cfg
Running urllib3-1.23/setup.py -q bdist_egg --dist-dir /tmp/easy_install-u9zkz5sn/urllib3-1.23/egg-dist-tmp-lp1t783z
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
warning: no previously-included files matching '*' found under directory 'docs/_build'
zip_safe flag not set; analyzing archive contents...
urllib3.packages.__pycache__.six.cpython-35: module references __path__
creating /mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.5/site-packages/urllib3-1.23-py3.5.egg
Extracting urllib3-1.23-py3.5.egg to /mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.5/site-packages
Adding urllib3 1.23 to easy-install.pth file

Installed /mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.5/site-packages/urllib3-1.23-py3.5.egg
Searching for tables==3.4.4
Reading https://pypi.python.org/simple/tables/
Best match: tables 3.4.4
Downloading https://files.pythonhosted.org/packages/4d/53/8f34ce887c2a2ad80518980419a5f6f41defc85a287a355987e559ce9385/tables-3.4.4.tar.gz#sha256=bdc5c073712af2a43babd139c4855fc99496bb2c3f3f5d1b4770a985e6f9ce29
Processing tables-3.4.4.tar.gz
Writing /tmp/easy_install-mk5x7pai/tables-3.4.4/setup.cfg
Running tables-3.4.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-mk5x7pai/tables-3.4.4/egg-dist-tmp-4xsidxjv
* Using Python 3.5.2 (default, Nov 23 2017, 16:37:01)
* USE_PKGCONFIG: False
/tmp/easy_install-mk5x7pai/tables-3.4.4/temp/H5close6lelobjv.c:1:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
 main (int argc, char **argv) {
 ^
/tmp/easy_install-mk5x7pai/tables-3.4.4/temp/H5close6lelobjv.c: In function ‘main’:
/tmp/easy_install-mk5x7pai/tables-3.4.4/temp/H5close6lelobjv.c:2:5: warning: implicit declaration of function ‘H5close’ [-Wimplicit-function-declaration]
     H5close();
     ^
/usr/bin/ld: cannot find -lhdf5
collect2: error: ld returned 1 exit status
.. ERROR:: Could not find a local HDF5 installation.
   You may need to explicitly state where your local HDF5 headers and
   library can be found by setting the ``HDF5_DIR`` environment
   variable or by using the ``--hdf5`` command-line option.
error: Setup script exited with 1
(cellxgene) root@woof:/mnt/c/Users/bruce/projects/cellxgene#
```

**Comment by csweaver** [comment]
Right now I'm only supporting Python 3.6 (due to scanpy issues). Is it possible to upgrade?

**Comment by bkmartinjr** [comment]
I can easily try python3.6.   But currently blocked by #150

**Comment by bkmartinjr** [comment]
With #150 fixed, I tried this again and it failed in another way.

I did a fresh install of python3.6, and then:
```
(cellxgene) root@woof:/mnt/c/Users/bruce/projects/cellxgene# python3.6 setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 2] No such file or directory: '/usr/lib/python3.6/site-packages/test-easy-install-13602.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/lib/python3.6/site-packages/

This directory does not currently exist.  Please create it and try again, or
choose a different installation directory (using the -d or --install-dir
option).

(cellxgene) root@woof:/mnt/c/Users/bruce/projects/cellxgene# ls /usr/lib/python3.6/site-packages
ls: cannot access '/usr/lib/python3.6/site-packages': No such file or directory
```

**Comment by csweaver** [comment]
It looks like if we use pip we get some magic that helps ease installation and placement of individual packages. Try this:
    # From inside the cellxgene directory
    pip install -e .

**Comment by bkmartinjr** [comment]
it seems to complete without errors (I just did it manually).   I have not yet confirmed that the full build completes (will do that later today)

**Comment by bkmartinjr** [comment]
With the latest change, we are getting closer!

Latest:
- build succeeds
- pip install succeeds
- running the example (scanpy) fails as it can't find a tk module

Maybe missing `python3-tk` from dependencies?

Error:
```
# cellxgene --title PBMC3K scanpy example-dataset/
font search path ['/mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf', '/mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/afm', '/mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts']
generated new fontManager
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 37, in <module>
    import _tkinter
ModuleNotFoundError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/bruce/projects/cellxgene/cellxgene/bin/cellxgene", line 11, in <module>
    load_entry_point('cellxgene', 'console_scripts', 'cellxgene')()
  File "/mnt/c/Users/bruce/projects/cellxgene/server/app/app.py", line 70, in main
    args.func(args)
  File "/mnt/c/Users/bruce/projects/cellxgene/server/app/app.py", line 55, in run_scanpy
    from .scanpy_engine.scanpy_engine import ScanpyEngine
  File "/mnt/c/Users/bruce/projects/cellxgene/server/app/scanpy_engine/scanpy_engine.py", line 4, in <module>
    import scanpy.api as sc
  File "/mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.6/site-packages/scanpy/api/__init__.py", line 269, in <module>
    from . import pl
  File "/mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.6/site-packages/scanpy/api/pl.py", line 1, in <module>
    from ..plotting.anndata import scatter, violin, ranking, clustermap
  File "/mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.6/site-packages/scanpy/plotting/anndata.py", line 7, in <module>
    from matplotlib import pyplot as pl
  File "/mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.6/site-packages/matplotlib/backends/tkagg.py", line 5, in <module>
    from six.moves import tkinter as Tk
  File "/mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.6/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.6/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/mnt/c/Users/bruce/projects/cellxgene/cellxgene/lib/python3.6/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 39, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package
#
```

**Comment by bkmartinjr** [comment]
@csweaver - closer!

With this change, the server runs and serves HTTP requests.   The client fails to load, getting an error (below).   This error is essentially the same problem you ran into with the crossfilter export, but is caused by a different module.

I have been debugging this (to try and fix crossfilter), so we should talk.    I think the core issue in this issue is fixed, and i'm fine if you close it.

```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Object.<anonymous> ((index):47)
    at Object.<anonymous> ((index):47)
    at t ((index):1)
    at Object.<anonymous> ((index):47)
    at Object.<anonymous> ((index):47)
    at t ((index):1)
    at Object.<anonymous> ((index):47)
    at t ((index):1)
    at Object.<anonymous> ((index):23)
    at t ((index):1)
    at Object.<anonymous> ((index):8)
    at t ((index):1)
    at Object.<anonymous> ((index):47)
    at t ((index):1)
    at Object.<anonymous> ((index):47)
    at t ((index):1)
    at Object.<anonymous> ((index):47)
    at t ((index):1)
    at Object.<anonymous> ((index):47)
    at t ((index):1)
    at Object.<anonymous> ((index):47)
    at t ((index):1)
    at Object.<anonymous> ((index):65)
    at t ((index):1)
    at (index):1
    at (index):1
```
