### ISSUE TITLE
Server unit tests fail for tiledb 0.6.0

### ISSUE THREAD

**Issue by mweiden** [chanzuckerberg/cellxgene#1454]
## Behavior

When running the server unit tests with tiledb 0.6.0 installed, you'll get this trace:

```
2020-05-05T15:29:48.3709846Z test_data_get_filter_fbs (server.test.test_api.EndPointsCxg) ... [2020-05-05 15:29:48,369] ERROR in app: Exception on /api/v0.2/data/var [GET]
2020-05-05T15:29:48.3710047Z Traceback (most recent call last):
2020-05-05T15:29:48.3711293Z   File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
2020-05-05T15:29:48.3711672Z     rv = self.dispatch_request()
2020-05-05T15:29:48.3712149Z   File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
2020-05-05T15:29:48.3712321Z     return self.view_functions[rule.endpoint](**req.view_args)
2020-05-05T15:29:48.3712687Z   File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/flask_restful/__init__.py", line 468, in wrapper
2020-05-05T15:29:48.3712830Z     resp = resource(*args, **kwargs)
2020-05-05T15:29:48.3713165Z   File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/flask/views.py", line 89, in view
2020-05-05T15:29:48.3713321Z     return self.dispatch_request(*args, **kwargs)
2020-05-05T15:29:48.3713690Z   File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
2020-05-05T15:29:48.3713851Z     resp = meth(*args, **kwargs)
2020-05-05T15:29:48.3714341Z   File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/server/app/app.py", line 35, in wrapper
2020-05-05T15:29:48.3714676Z     response = make_response(f(*args, **kwargs))
2020-05-05T15:29:48.3715236Z   File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/server/app/app.py", line 119, in wrapped_function
2020-05-05T15:29:48.3715368Z     return func(self, data_adaptor)
2020-05-05T15:29:48.3715677Z   File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/server/app/app.py", line 210, in get
2020-05-05T15:29:48.3715828Z     return common_rest.data_var_get(request, data_adaptor)
2020-05-05T15:29:48.3716166Z   File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/server/common/rest.py", line 220, in data_var_get
2020-05-05T15:29:48.3716302Z     data_adaptor.data_frame_to_fbs_matrix(filter, axis=Axis.VAR),
2020-05-05T15:29:48.3716668Z   File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/server/data_common/data_adaptor.py", line 279, in data_frame_to_fbs_matrix
2020-05-05T15:29:48.3716810Z     X = self.get_X_array(obs_selector, var_selector)
2020-05-05T15:29:48.3717142Z   File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/server/data_cxg/cxg_adaptor.py", line 210, in get_X_array
2020-05-05T15:29:48.3717292Z     data = X.multi_index[obs_items, var_items][""]
2020-05-05T15:29:48.3717857Z KeyError: ''
```

## Steps to reproduce

1. `make build-for-server-dev install-dev`
1. `cd server`
1. `make unit-test`

## Notes

I think it has something to do with this diff https://github.com/TileDB-Inc/TileDB-Py/commit/8c59159705b8733b0d8ecd72fa063bed18d0e8a0

**Comment by mweiden** [comment]
We must roll back https://github.com/chanzuckerberg/cellxgene/pull/1453 once this is fixed.

**Comment by bmccandless** [comment]
Fixed, in tiledb 0.6.1
