### ISSUE TITLE
CXG driver will attempt to load entire X matrix when filter has no matches

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1499]
If the REST API is asked for a column, via /data/var, using an annotation value filter that matches nothing (ie, has an empty match), the cxg_adaptor attempts to load and return the entire X matrix (rather than an empty result).

Concretely:
> GET <dataset>/api/v0.2/data/var?var:name_0=UNKNOWN_NAME

This _should_ return an empty dataframe or error, but instead attempts to return the entire X matrix.  Usually this results in on out-of-memory condition in the flatbuffer serialization code, and a hard error.

This could easily be used as a denial-of-service attack surface.

I think the root cause is inside `pack_selector_from_mask()`.   It fails to check if the result of `np.nonzero` is zero length, and instead returns `slice(None, None, None)` (ie, same as 'all')

**Comment by bkmartinjr** [comment]
Example stack trace from running in debug mode (in this case, the dataset did not have a gene named Zhx1)
```
INFO:werkzeug:127.0.0.1 - - [28/May/2020 15:15:35] "GET /api/v0.2/data/var?var:name_0=Zhx1 HTTP/1.1" 500 -
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/mnt/c/Users/bruce/projects/cellxgene/server/app/app.py", line 35, in wrapper
    response = make_response(f(*args, **kwargs))
  File "/mnt/c/Users/bruce/projects/cellxgene/server/app/app.py", line 119, in wrapped_function
    return func(self, data_adaptor)
  File "/mnt/c/Users/bruce/projects/cellxgene/server/app/app.py", line 210, in get
    return common_rest.data_var_get(request, data_adaptor)
  File "/mnt/c/Users/bruce/projects/cellxgene/server/common/rest.py", line 220, in data_var_get
    data_adaptor.data_frame_to_fbs_matrix(filter, axis=Axis.VAR),
  File "/mnt/c/Users/bruce/projects/cellxgene/server/data_common/data_adaptor.py", line 282, in data_frame_to_fbs_matrix
    return encode_matrix_fbs(X, col_idx=col_idx, row_idx=None)
  File "/mnt/c/Users/bruce/projects/cellxgene/server/data_common/fbs/matrix.py", line 186, in encode_matrix_fbs
    builder = flatbuffers.Builder(guess_at_mem_needed(matrix))
  File "/mnt/c/Users/bruce/projects/cellxgene/venv38/lib/python3.8/site-packages/flatbuffers/builder.py", line 124, in __init__
    raise BuilderSizeError(msg)
flatbuffers.builder.BuilderSizeError: flatbuffers: Cannot create Builder larger than 2 gigabytes.
```
