### ISSUE TITLE
[BUG] pip install of cellxgene in a conda environment fails with tiledb "image not found"

### ISSUE THREAD

**Issue by bmccandless** [chanzuckerberg/cellxgene#1978]
**Describe the bug**

From:  https://cziscience.slack.com/archives/C8ME9JMBP/p1604955568138000

Hi all, I've started a conda environment and pip-installed cellxgene. I am attempting to run through the example data:

```
cellxgene launch https://cellxgene-example-data.czi.technology/pbmc3k.h5ad
```

and i've run into an error:

```
OSError: dlopen(libtiledb.dylib, 6): image not found
```

txt file attached with the entire error message.
Any insight? I see there has been some buzz surrounding tileDB on the github issues tab

```
error_message.txt 
Traceback (most recent call last):
  File "/Users/colephalen/cellxgene/lib/python3.7/site-packages/tiledb/__init__.py", line 20, in <module>
    from .libtiledb import Ctx
ImportError: dlopen(/Users/colephalen/cellxgene/lib/python3.7/site-packages/tiledb/libtiledb.cpython-37m-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/colephalen/cellxgene/lib/python3.7/site-packages/tiledb/.dylibs/libintl.8.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/colephalen/cellxgene/lib/python3.7/site-packages/tiledb/.dylibs/libintl.8.dylib
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/colephalen/cellxgene/lib/python3.7/site-packages/tiledb/__init__.py", line 24, in <module>
    ctypes.CDLL(os.path.join(lib_dir, lib_name))
  File "/opt/miniconda3/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/colephalen/cellxgene/lib/python3.7/site-packages/tiledb/native/libtiledb.dylib, 6): image not found
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/colephalen/cellxgene/bin/cellxgene", line 11, in <module>
    load_entry_point('cellxgene==0.16.5', 'console_scripts', 'cellxgene')()
  File "/Users/colephalen/cellxgene/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/colephalen/cellxgene/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Users/colephalen/cellxgene/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Users/colephalen/cellxgene/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/colephalen/cellxgene/lib/python3.7/site-packages/server/cli/cli.py", line 3, in <module>
    from .convert_to_cxg import convert_to_cxg
  File "/Users/colephalen/cellxgene/lib/python3.7/site-packages/server/cli/convert_to_cxg.py", line 5, in <module>
    from server.converters.h5ad_data_file import H5ADDataFile
  File "/Users/colephalen/cellxgene/lib/python3.7/site-packages/server/converters/h5ad_data_file.py", line 7, in <module>
    import tiledb
  File "/Users/colephalen/cellxgene/lib/python3.7/site-packages/tiledb/__init__.py", line 27, in <module>
    ctypes.CDLL(lib_name)
  File "/opt/miniconda3/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libtiledb.dylib, 6): image not found
```

**Comment by kruegert** [comment]
I installed cellxgene with pip in a conda environment. I'm getting the same error (I'm on a PC, Win 10 Pro). Any update? Thanks.

**Comment by bmccandless** [comment]
Hello @kruegert, I'm taking a look at this today with the tiledb team.   
It may help in our debugging if you could supply the output of `conda list`.

**Comment by bmccandless** [comment]
@kruegert

@ihnorton from TileDB has identified the problem and has a workaround:

Looking for a fix now and will do a new release ASAP, but the following should work temporarily:
```
# after `pip install cellxgene`
pip uninstall tiledb
conda install tiledb-py
```

Can you please give that a try and see if it unblocks you?

**Comment by kruegert** [comment]
@bmccandless yes, that works! Thanks

**Comment by ihnorton** [comment]
Hi @bmccandless, @kruegert, this is fixed for pip installs in the latest TileDB-Py release 0.7.1 (https://pypi.org/project/tiledb/0.7.1/).
