### ISSUE TITLE
Memory error on GET

### ISSUE THREAD

**Issue by csweaver** [chanzuckerberg/cellxgene#23]
$ curl http://tabulamuris.cxg.czi.technology/api/v0.1/expression

Traceback (most recent call last):  
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in *call*  
return self.wsgi_app(environ, start_response)  
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app  
response = self.handle_exception(e)  
File "/usr/local/lib/python3.5/dist-packages/flask_restful/*init*.py", line 273, in error_router  
return original_handler(e)  
File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function  
return cors_after_request(app.make_response(f(*args, **kwargs)))  
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception  
reraise(exc_type, exc_value, tb)  
File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 32, in reraise  
raise value.with_traceback(tb)  
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app  
response = self.full_dispatch_request()  
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request  
rv = self.handle_user_exception(e)  
File "/usr/local/lib/python3.5/dist-packages/flask_restful/*init*.py", line 273, in error_router  
return original_handler(e)  
File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function  
return cors_after_request(app.make_response(f(*args, **kwargs)))  
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception  
reraise(exc_type, exc_value, tb)  
File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 32, in reraise  
raise value.with_traceback(tb)  
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request  
rv = self.dispatch_request()  
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request  
return self.view_functions<**req.view_args|rule.endpoint>  
File "/usr/local/lib/python3.5/dist-packages/flask_restful/*init*.py", line 480, in wrapper  
resp = resource(*args, **kwargs)  
File "/usr/local/lib/python3.5/dist-packages/flask_restful_swagger_2/*init*.py", line 39, in decorator  
return f(*args, **kwargs)  
File "/usr/local/lib/python3.5/dist-packages/flask/views.py", line 84, in view  
return self.dispatch_request(*args, **kwargs)  
File "/usr/local/lib/python3.5/dist-packages/flask_restful/*init*.py", line 595, in dispatch_request  
resp = meth(*args, **kwargs)  
File "/usr/local/lib/python3.5/dist-packages/flask_restful_swagger_2/swagger.py", line 219, in inner  
return f(self, *args, **kwargs)  
File "/app/application.py", line 1028, in get  
data = parse_exp_data(limit=40, unexpressed_genes=unexpressed_genes)  
File "/app/application.py", line 294, in parse_exp_data  
expression = get_expression(cells, genes)  
File "/app/application.py", line 351, in get_expression  
raise error  
File "/app/application.py", line 345, in get_expression  
expression = e.getDenseExpressionMatrix("AllGenes", cellset)  
MemoryError: std::bad_alloc

**Comment by bkmartinjr** [comment]
Note that this API call is not something the f/e will do - I just accidentally did it from the command line while exploring the API.   You could probably delay this fix if there are higher priority work items.

**Comment by mckinsel** [comment]
I suspect you'd hit the same issue calculating differential expression with big enough cell selections. The calls to `getDenseExpressionMatrix` are probably a little risky in general.
