### ISSUE TITLE
[BUG] Incorrect `tag_name` formatting in latest release

### ISSUE THREAD

**Issue by mukundctx** [chanzuckerberg/cellxgene#2449]
**Describe the bug**
`_request_cellxgene_releases` suggests that the latest version is `0.19`.
However, the `version_gt` function expects the version number to have a major, minor and patch number. This causes an error when trying to launch a new cellxgene instance. 

Error Details as follows
```
<h4 style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.5rem; font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-weight: 500; line-height: 1.2; color: rgb(33, 37, 41); font-size: 1.5rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Error Details</h4>

Message | Cellxgene failed to launch dataset.
-- | --
500
None
Traceback (most recent call last): File "/usr/local/bin/cellxgene", line 8, in <module> sys.exit(cli()) File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__ return self.main(*args, **kwargs) File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main rv = self.invoke(ctx) File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1256, in invoke Command.invoke(self, ctx) File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke return ctx.invoke(self.callback, **ctx.params) File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke return callback(*args, **kwargs) File "/usr/local/lib/python3.7/site-packages/backend/server/cli/cli.py", line 28, in cli log_upgrade_check() File "/usr/local/lib/python3.7/site-packages/backend/server/cli/upgrade.py", line 25, in log_upgrade_check if version_gt(latest_release, __version__): File "/usr/local/lib/python3.7/site-packages/backend/server/cli/upgrade.py", line 80, in version_gt for left, right in zip(split_version(left_version), split_version(right_version)): File "/usr/local/lib/python3.7/site-packages/backend/server/cli/upgrade.py", line 76, in split_version return [int(match.group(group)) for group in ["major", "minor", "patch"]] File "/usr/local/lib/python3.7/site-packages/backend/server/cli/upgrade.py", line 76, in <listcomp> return [int(match.group(group)) for group in ["major", "minor", "patch"]] AttributeError: 'NoneType' object has no attribute 'group'

<br class="Apple-interchange-newline">
```

**To Reproduce**
1. Try to launch a new cellxgene instance.
2. See the error above

**Expected behavior**
How to fix: Fig tag name from 0.19 to 0.19.0

**Screenshots**
![image](https://user-images.githubusercontent.com/57632184/135195992-470b7625-c7c7-42b6-a961-58d76aa1d6c3.png)

**Version (please complete the following information):**
 - Desktop or hosted?: Hosted
 - Browser (if hosted) [e.g. chrome, safari]: Chrome
 - Version [e.g. 0.13.0]: 0.17.0

**Additional context**

**Comment by blrnw3** [comment]
Resolved
