### ISSUE TITLE
Compatibility tests are failing on python 3.6

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/cellxgene#2494]
I believe our version of actions/setup-python is out of date.  Version 2 allows for the downloading of python version from actions/python-versions.

**Comment by metakuni** [comment]
I'm guessing that this is no longer in progress...

@seve / @roaga ?

**Comment by metakuni** [comment]
```
seve
:spiral_calendar_pad: Today at 10:29
compatibility tests are failing again, for a new reason. Does this error look familiar to anyone?

seve
:spiral_calendar_pad:  5 minutes ago
Traceback (most recent call last):
  File "/home/runner/work/cellxgene/cellxgene/test/unit/cli/test_annotate.py", line 44, in test__annotate__loads_and_runs
    model_file_path = write_model(FakeModel())
  File "/home/runner/work/cellxgene/cellxgene/test/unit/cli/test_annotate.py", line 18, in write_model
    code_path=[fixtures_path])
  File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/mlflow/pyfunc/__init__.py", line 1068, in save_model
    message="Path '{}' already exists".format(path), error_code=RESOURCE_ALREADY_EXISTS
mlflow.exceptions.MlflowException: Path '/tmp/tmpgro4oapm' already exists
```

**Comment by seve** [comment]
Above failure is expected and not relevant to ticket
