### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MaximilianLombardo** [chanzuckerberg/cellxgene#2567]
**Describe the bug**

Attempting to install and run pip release v1.1.0, unable to execute `annotate` subcommand - I eventually arrive at the following errors:

`FileNotFoundError: [Errno 2] No such file or directory: 'mlflow'` and `ModuleNotFoundError: No module named 'scanpy'` after installing `cellxgene` v1.1.0 in a fresh `conda` environment  

**To Reproduce**

commands:

```
conda create -n "annoTEST2" python=3.9
conda activate annoTEST2
pip install cellxgene
cellxgene annotate -h
cellxgene annotate -i pbmc3k.h5ad -m immune_ref_20220728145305_conda.zip -o pbmc3kAnnotated.h5ad
```

output:

```
(annoTEST2) mlombardo@CZIMACOS3301 test % cellxgene annotate -i pbmc3k.h5ad -m immune_ref_20220728145305_conda.zip -o pbmc3kAnnotated.h5ad
Reading query dataset pbmc3k.h5ad...
Using cached model at .models_cache/immune_ref_20220728145305_conda
Annotating pbmc3k.h5ad with cell_type...
Traceback (most recent call last):
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST2/bin/cellxgene", line 8, in <module>
    sys.exit(cli())
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST2/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST2/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST2/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST2/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST2/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST2/lib/python3.9/site-packages/server/cli/annotate.py", line 189, in annotate
    p = subprocess.Popen(
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST2/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST2/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mlflow'
```

I install `mlflow` and run the same `annotate` command, and get the following error:

```
(annoTEST2) mlombardo@CZIMACOS3301 test % cellxgene annotate -i pbmc3k.h5ad -m immune_ref_20220728145305_conda.zip -o pbmc3kAnnotated.h5ad
Reading query dataset pbmc3k.h5ad...
Using cached model at .models_cache/immune_ref_20220728145305_conda
Annotating pbmc3k.h5ad with cell_type...
/Users/mlombardo/opt/anaconda3/envs/annoTEST2/lib/python3.9/site-packages/click/core.py:2322: UserWarning: Virtualenv support is still experimental and may be changed in a future release without warning.
  value = self.callback(ctx, self, value)
2022/09/09 00:07:34 INFO mlflow.models.cli: Selected backend for flavor 'python_function'
2022/09/09 00:07:34 INFO mlflow.utils.virtualenv: Installing python 3.9.13 if it does not exist
2022/09/09 00:07:34 INFO mlflow.utils.virtualenv: Environment /Users/mlombardo/.mlflow/envs/mlflow-155420bfe319af3b067b955e140aacfc86c2669e already exists
2022/09/09 00:07:34 INFO mlflow.utils.virtualenv: Running command: bash -c source /Users/mlombardo/.mlflow/envs/mlflow-155420bfe319af3b067b955e140aacfc86c2669e/bin/activate && python -c "from mlflow.pyfunc.scoring_server import _predict; _predict(model_uri='file:///Users/mlombardo/Downloads/test/.models_cache/immune_ref_20220728145305_conda', input_path='/var/folders/1v/yhtk99j50v351lg25mn8yz200000gq/T/tmpx4xmnf_7', output_path=None, content_type='csv', json_format='split')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mlombardo/.mlflow/envs/mlflow-155420bfe319af3b067b955e140aacfc86c2669e/lib/python3.9/site-packages/mlflow/pyfunc/scoring_server/__init__.py", line 330, in _predict
    pyfunc_model = load_model(model_uri)
  File "/Users/mlombardo/.mlflow/envs/mlflow-155420bfe319af3b067b955e140aacfc86c2669e/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py", line 756, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/Users/mlombardo/.pyenv/versions/3.9.13/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/mlombardo/Downloads/test/.models_cache/immune_ref_20220728145305_conda/code/cell_type/mlflow_model_loader/__init__.py", line 1, in <module>
    from cell_type.mlflow_model_loader.model_wrapper import CellTypeAnnotationModelWrapper
  File "/Users/mlombardo/Downloads/test/.models_cache/immune_ref_20220728145305_conda/code/cell_type/mlflow_model_loader/model_wrapper.py", line 3, in <module>
    import scanpy
ModuleNotFoundError: No module named 'scanpy'
Traceback (most recent call last):
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST2/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST2/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST2/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST2/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST2/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST2/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST2/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST2/lib/python3.9/site-packages/mlflow/models/cli.py", line 125, in predict
    return _get_flavor_backend(
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST2/lib/python3.9/site-packages/mlflow/pyfunc/backend.py", line 133, in predict
    return _execute_in_virtualenv(
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST2/lib/python3.9/site-packages/mlflow/utils/virtualenv.py", line 338, in _execute_in_virtualenv
    return _exec_cmd(
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST2/lib/python3.9/site-packages/mlflow/utils/process.py", line 116, in _exec_cmd
    raise ShellCommandException.from_completed_process(comp_process)
mlflow.utils.process.ShellCommandException: Non-zero exit code: 1
Command: ['bash', '-c', 'source /Users/mlombardo/.mlflow/envs/mlflow-155420bfe319af3b067b955e140aacfc86c2669e/bin/activate && python -c "from mlflow.pyfunc.scoring_server import _predict; _predict(model_uri=\'file:///Users/mlombardo/Downloads/test/.models_cache/immune_ref_20220728145305_conda\', input_path=\'/var/folders/1v/yhtk99j50v351lg25mn8yz200000gq/T/tmpx4xmnf_7\', output_path=None, content_type=\'csv\', json_format=\'split\')"']
Annotation failed!

```

I encounter the same error even after installing `scanpy`

**Expected behavior**
To run the full annotation

**Screenshots**

**Version (please complete the following information):**
 - Desktop or hosted?: Desktop
 - Browser (if hosted) [e.g. chrome, safari]:
 - Version [e.g. 0.13.0]:

**Additional context**

**Comment by atolopko-czi** [comment]
@MaximilianLombardo 
1. On pip install, did you specify `cellxgene[annotate]` or `cellxgene`? The former should install the mlflow package, addressing your first problem with mlflow not being installed.
2. On `cellxgene annotate`, be sure to specify `--mlflow-env-manager conda`, since that appears to be missing the cmd you tried. Otherwise, the mlflow model is run a new virtualenv, but "nested" within an activate conda env, and this was causing pip package loading problems.

Let me know if these fixes solve the reported problems.

**Comment by MaximilianLombardo** [comment]
@atolopko-czi 

Thanks Andrew!

w.r.t. to the first issue:

So I run `pip install cellxgene[annotate]` and get the response `zsh: no matches found: cellxgene[annotate]`

To the second issue:
> On cellxgene annotate, be sure to specify --mlflow-env-manager conda, since that appears to be missing the cmd you tried. Otherwise, the mlflow model is run a new virtualenv, but "nested" within an activate conda env, and this was causing pip package loading problems.

ah ok - sorry to have missed that, thank you for the explanation!

**Comment by MaximilianLombardo** [comment]
@atolopko-czi I'm realizing that for the first issue - I needed to run it like so:

`pip install 'cellxgene[annotate]'`

The installation seems to have worked via that method - testing the rest of the workflow and will report back with any issues.

**Comment by MaximilianLombardo** [comment]
@atolopko-czi 

was able to move forward with pipeline - got a new issue related to not being able to find features in common between the reference and query dataset[`ValueError: No reference var names found in query data. Please rerun with return_reference_var_names=True to see reference var names.
`]

I tried running with the following command, with a dataset downloaded from the data portal (49 years old male - Airway Wash (3 days post-intubation) From [this](https://cellxgene.cziscience.com/collections/29f92179-ca10-4309-a32b-d383d80347c1) collection) as a test dataset:

command:

`cellxgene annotate -i airway.h5ad -m immune_ref_20220728145305_conda.zip -o airwayAnnotated.h5ad --mlflow-env-manager conda --organism 'Homo sapiens'`

output:

```
(annoTEST3) mlombardo@CZIMACOS3301 test % cellxgene annotate -i airway.h5ad -m immune_ref_20220728145305_conda.zip -o airwayAnnotated.h5ad --mlflow-env-manager conda --organism 'Homo sapiens'
Reading query dataset airway.h5ad...
Using cached model at .models_cache/immune_ref_20220728145305_conda
Annotating airway.h5ad with cell_type...
2022/09/12 12:32:12 INFO mlflow.models.cli: Selected backend for flavor 'python_function'
2022/09/12 12:32:14 INFO mlflow.utils.conda: Conda environment mlflow-caa73ed6c4085170ab48a764eb6fdc61b3112b78 already exists.
2022/09/12 12:32:14 INFO mlflow.pyfunc.backend: === Running command 'source /Users/mlombardo/opt/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-caa73ed6c4085170ab48a764eb6fdc61b3112b78 1>&2 && python -c "from mlflow.pyfunc.scoring_server import _predict; _predict(model_uri='file:///Users/mlombardo/Downloads/test/.models_cache/immune_ref_20220728145305_conda', input_path='/var/folders/1v/yhtk99j50v351lg25mn8yz200000gq/T/tmph05zqets', output_path=None, content_type='csv', json_format='split')"'
/Users/mlombardo/opt/anaconda3/envs/mlflow-caa73ed6c4085170ab48a764eb6fdc61b3112b78/lib/python3.9/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
Global seed set to 0
/Users/mlombardo/opt/anaconda3/envs/mlflow-caa73ed6c4085170ab48a764eb6fdc61b3112b78/lib/python3.9/site-packages/chex/_src/pytypes.py:37: FutureWarning: jax.tree_structure is deprecated, and will be removed in a future release. Use jax.tree_util.tree_structure instead.
  PyTreeDef = type(jax.tree_structure(None))
_load_pyfunc(data_path=/Users/mlombardo/Downloads/test/.models_cache/immune_ref_20220728145305_conda/data/immune_ref)
artifacts_path=/Users/mlombardo/Downloads/test/.models_cache/immune_ref_20220728145305_conda/data/immune_ref
input={'query_dataset_h5ad_path': 'airway.h5ad', 'output_h5ad_path': 'airwayAnnotated.h5ad', 'annotation_prefix': 'cxg_cell_type', 'classifier': 'default', 'organism': 'Homo sapiens', 'use_gpu': True}
INFO     File
         /Users/mlombardo/Downloads/test/.models_cache/immune_ref_20220728145305
         _conda/data/immune_ref/model.pt already downloaded
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mlombardo/opt/anaconda3/envs/mlflow-caa73ed6c4085170ab48a764eb6fdc61b3112b78/lib/python3.9/site-packages/mlflow/pyfunc/scoring_server/__init__.py", line 342, in _predict
    predictions_to_json(pyfunc_model.predict(df), sys.stdout)
  File "/Users/mlombardo/opt/anaconda3/envs/mlflow-caa73ed6c4085170ab48a764eb6fdc61b3112b78/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py", line 631, in predict
    return self._model_impl.predict(data)
  File "/Users/mlombardo/Downloads/test/.models_cache/immune_ref_20220728145305_conda/code/cell_type/mlflow_model_loader/model_wrapper.py", line 29, in predict
    annotate(query_dataset,
  File "/Users/mlombardo/Downloads/test/.models_cache/immune_ref_20220728145305_conda/code/cell_type/predict.py", line 60, in annotate
    query_dataset_prepped = prep_query_data(query_dataset,
  File "/Users/mlombardo/Downloads/test/.models_cache/immune_ref_20220728145305_conda/code/cell_type/prepare.py", line 104, in prep_query_data
    scvi.model.SCANVI.prepare_query_anndata(adata_query, model_path)
  File "/Users/mlombardo/opt/anaconda3/envs/mlflow-caa73ed6c4085170ab48a764eb6fdc61b3112b78/lib/python3.9/site-packages/scvi/model/base/_archesmixin.py", line 195, in prepare_query_anndata
    raise ValueError(
ValueError: No reference var names found in query data. Please rerun with return_reference_var_names=True to see reference var names.
Traceback (most recent call last):
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST3/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST3/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST3/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST3/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST3/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST3/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST3/lib/python3.9/site-packages/mlflow/models/cli.py", line 125, in predict
    return _get_flavor_backend(
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST3/lib/python3.9/site-packages/mlflow/pyfunc/backend.py", line 126, in predict
    return _execute_in_conda_env(
  File "/Users/mlombardo/opt/anaconda3/envs/annoTEST3/lib/python3.9/site-packages/mlflow/pyfunc/backend.py", line 420, in _execute_in_conda_env
    raise Exception(
Exception: Command 'source /Users/mlombardo/opt/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-caa73ed6c4085170ab48a764eb6fdc61b3112b78 1>&2 && python -c "from mlflow.pyfunc.scoring_server import _predict; _predict(model_uri='file:///Users/mlombardo/Downloads/test/.models_cache/immune_ref_20220728145305_conda', input_path='/var/folders/1v/yhtk99j50v351lg25mn8yz200000gq/T/tmph05zqets', output_path=None, content_type='csv', json_format='split')"' returned non zero return code. Return code = 1
Annotation failed!

```

**Comment by atolopko-czi** [comment]
> ValueError: No reference var names found in query data.

You probably need to specify `--gene-column-name`. It defaults to the `obs.index` column if not specified.  For CxG schema-compliant h5ads, use `--gene-column-name feature_name`.

**Comment by MaximilianLombardo** [comment]
Ok that worked, and I also needed to specify the `--no-use-gpu` to get a successful run, just documenting here so that I can replicate in the docs - full command for reference:

`cellxgene annotate -i airway.h5ad -m immune_ref_20220728145305_conda.zip -o airwayAnnotated.h5ad --mlflow-env-manager conda --organism 'Homo sapiens' --gene-column-name feature_name --no-use-gpu`

**Comment by MaximilianLombardo** [comment]
yes, closing!
