### ISSUE TITLE
[BUG] GET http://localhost:5005/api/v0.2/colors: 404 (NOT FOUND)

### ISSUE THREAD

**Issue by alexlenail** [chanzuckerberg/cellxgene#2598]
**Describe the bug**
Just installed cellxgene, and tried to load a dataset of mine, got this error and fails to load. 

**Version (please complete the following information):**
 - Desktop or hosted?: pip installed on local machine
 - Browser (if hosted) [e.g. chrome, safari]: chrome
 - Version [e.g. 0.13.0]: cellxgene-1.1.1

**Comment by alexlenail** [comment]
```
 cellxgene launch https://github.com/chanzuckerberg/cellxgene/raw/main/example-dataset/pbmc3k.h5ad
```
does work though. Could it have to do with this warning? 

```
[cellxgene] Warning: Var annotation 'index' has 32507 categories, this may be cumbersome or slow to display. We recommend setting the --max-category-items option to 500, this will hide categorical annotations with more than 500 categories in the UI
```

**Comment by alexlenail** [comment]
A little more digging: 

```
DEBUG:server.app.app:Unknown color format type!
Traceback (most recent call last):
  File "/Users/alex/miniconda3/envs/py39/lib/python3.9/site-packages/server/common/colors.py", line 187, in convert_color_to_hex_format
    raise ColorFormatException("Unknown color format type!")
server.common.errors.ColorFormatException: Unknown color format type!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alex/miniconda3/envs/py39/lib/python3.9/site-packages/server/common/rest.py", line 243, in colors_get
    return make_response(jsonify(data_adaptor.get_colors()), HTTPStatus.OK)
  File "/Users/alex/miniconda3/envs/py39/lib/python3.9/site-packages/server/data_anndata/anndata_adaptor.py", line 334, in get_colors
    return convert_anndata_category_colors_to_cxg_category_colors(self.data)
  File "/Users/alex/miniconda3/envs/py39/lib/python3.9/site-packages/server/common/colors.py", line 231, in convert_anndata_category_colors_to_cxg_category_colors
    zip(data.obs[category_name].cat.categories, [convert_color_to_hex_format(c) for c in data.uns[uns_key]])
  File "/Users/alex/miniconda3/envs/py39/lib/python3.9/site-packages/server/common/colors.py", line 231, in <listcomp>
    zip(data.obs[category_name].cat.categories, [convert_color_to_hex_format(c) for c in data.uns[uns_key]])
  File "/Users/alex/miniconda3/envs/py39/lib/python3.9/site-packages/server/common/colors.py", line 189, in convert_color_to_hex_format
    raise ColorFormatException(e)
server.common.errors.ColorFormatException: Unknown color format type!

```

**Comment by alexlenail** [comment]
Removing all my colors from `.uns` seems to have solved it. My colors were in the format: 
```
'majority_voting_colors': ['#b9342cff', '#873c46ff', '#996068ff', ...
```
They display properly when I make UMAPs in scanpy..

**Comment by alexlenail** [comment]
Oh that's interesting -- they're all hex rgb*a*...

**Comment by MaximilianLombardo** [comment]
Hey Alex - am I correct in understanding that you have resolved your own issue?

**Comment by MaximilianLombardo** [comment]
ps which version of scanpy did you generate your dataset with?

**Comment by alexlenail** [comment]
scanpy==1.9.1, python 3.9.13, macOS 12.5.1

**Comment by MaximilianLombardo** [comment]
perfect, thanks!
