### ISSUE TITLE
[BUG] Cellxgene failing to launch h5ad files

### ISSUE THREAD

**Issue by chryssiebrown** [chanzuckerberg/cellxgene#2625]
**Describe the bug**
Receive the following error message when launching recently generated h5ad files 

Error: File not found or is inaccessible. File must be an .h5ad object

I can launch other h5ad files in the same google drive folder and am also able to launch the files that I am having issues with when I use a different iMAC 

**To Reproduce**
From the terminal:
cellxgene launch /Users/xxxx/Library/CloudStorage/GoogleDrive-xxxx/My\ Drive/xxx\ xx/cellxgene/xxxx.h5ad 

**Expected behavior**
Files would usually launch

**Screenshots**

**Version (please complete the following information):**
 - MAC
 - Safari
 - MAC OS Ventura 13.4

**Additional context**

**Comment by MaximilianLombardo** [comment]
Hey Chryssie - thanks - can you launch an h5ad with cellxgene when they are saved outside of your google drive folder?

Max

**Comment by chryssiebrown** [comment]
Hi Max,

I get the same error message if I try and launch it from e.g. my Downloads folder,

Chryssie

**Comment by chryssiebrown** [comment]
Hi Max,Just following up on this - let me know if there is anything else I can try,Thanks,ChrysOn 16 Aug 2023, at 17:05, Chrysothemis Brown ***@***.***> wrote:﻿Hi Max,I get the same error message if I try and launch it from e.g. my Downloads folder,ChryssieOn Aug 16, 2023, at 4:24 PM, MaximilianLombardo ***@***.***> wrote:Hey Chryssie - thanks - can you launch an h5ad with cellxgene when they are saved outside of your google drive folder?Max—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Fougere87** [comment]
Hi everyone,
I had the same problem here when trying to read a recent h5ad file through a docker instance of cellxgene. 
What is strange is that all my "old" h5ad files could be read without any problem. 
No problem loading the file in scanpy as well

It seems to be related to old versions of python because numba cannot update with a python env below 3.8.
Using 3.9 or 3.10 python or env everything works perfectly. 

Hope it helps !

**Comment by MaximilianLombardo** [comment]
@Fougere87 thanks for the suggestion! @chryssiebrown what version of python are you running? Does this fix the issue for you?

Hey @chryssiebrown, if that does not solve your problem, are you able to share the data file that is giving you trouble? Would you also be able to share the following info?
- With what version was the file created?
- Is that the same version as the files that work with CELLxGENE currently?
- Could you also share the more complete stack trace here?

Apologies for the inundation of questions

**Comment by chryssiebrown** [comment]
Thanks for the suggestion - the problem sounds identical, I could read old h5ad files without any problem but only have issues with recent h5ad.
I checked the version of python though and it’s 3.9.6 which should be ok? I can try updating.

I will check the version of python used for creating recent vs old files,

Thanks,
Chrys

**Comment by yyoshiaki** [comment]
Hi everyone,

I got the same error with the docker container in several independent environments. You could reproduce the error as follows;

## 1. Docker setup

```
git clone https://github.com/chanzuckerberg/cellxgene.git
cd cellxgene
docker build . -t cellxgene
```

## 2. h5ad prep

```
import scanpy as sc

adata = sc.datasets.pbmc3k_processed()
adata.write('pbmc3k.h5ad')
```

my env
```
python 3.9.16
scanpy==1.9.3 anndata==0.9.1 umap==0.5.3 numpy==1.22.4 scipy==1.9.1 pandas==1.3.5 scikit-learn==1.2.2 statsmodels==0.14.0 python-igraph==0.10.4 pynndescent==0.5.10
```

## 3. launch cellxgene

```
docker run -v "$PWD:/data/" -p 5005:5005 cellxgene launch --host 0.0.0.0 data/pbmc3k.h5ad 
```

Error

```
[cellxgene] Starting the CLI...
[cellxgene] Loading data from pbmc3k.h5ad.
Error: File not found or is inaccessible. File must be an .h5ad object. Please check your input and try again.
```

The weird thing is that https://github.com/chanzuckerberg/cellxgene/raw/main/example-dataset/pbmc3k.h5ad worked well.

Best,
Yoshi

**Comment by Fougere87** [comment]
@yyoshiaki Yes that's all ok, but as you are running the dockerfile from the repo which uses ubuntu:bionic (18.04 :-D) as a base image. 
Therefore, in your docker env, you have python 3.6. 
Try running 
docker -it run -v "$PWD:/data/" -p 5005:5005 --entrypoint bash cellxgene 
and then launch python to see the version. 
 
@chryssiebrown have you checked your numba and h5py versions ? Are you launching cellxgene from docker or in your terminal ? 


Best,
Chlo

**Comment by yyoshiaki** [comment]
@Fougere87 Thank you so much for your quick response.
I checked python and library versions by `docker run -it -v "$PWD:/data/" -p 5005:5005 --entrypoint bash cellxgene`.
Python 3.6.9, anndata==0.7.8, h5py==3.1.0 were installed.

By changing the base image from bionic to jammy, for example, I could fix the problem, #2628

Thank you,
Yoshi

**Comment by chryssiebrown** [comment]
That was very helpful - I had the newer version of python 3.9 but in my environment I was using python 3.6.9. I updated and that fixed the issue! Thanks all for your help,

Chrys

**Comment by chryssiebrown** [comment]
Hi,

Unfortunately although that fixed the issue on my desktop, I am having the same issue on my MacBook, running cellxgene from the terminal. I have python 3.11.4 installed on my Mac. I also tried creating an environment with Python 3.9 and receive the same message as previously - I am still able to load older .5ad files, but not the recent ones.

Thanks for your help,
Chrys

Error: File not found or is inaccessible. File must be an .h5ad object. Please check your input and try again.

**Comment by timslittle** [comment]
Chryssie I hope that you solved this issue, but in case it is helpful I was having similar problems despite up-to-date Python etc, and it turned out that the issue was that I was compressing the h5ad file in a way that Cellxgene couldn't recognise.

**Comment by johannesnicolaus** [comment]
Hi all, is there any update regarding this? I'm getting the same issue but haven't found any fix. I'm not even sure where to start to troubleshoot. This is the full error message. Maybe the anndata should be updated?

```
Error: File not found or is inaccessible. File must be an .h5ad object. Please check your input and try again.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/server/data_anndata/anndata_adaptor.py", line 164, in _load_data
    self.data = anndata.read_h5ad(lh, backed=backed)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anndata/_io/h5ad.py", line 258, in read_h5ad
    adata = read_dispatched(f, callback=callback)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anndata/experimental/_dispatch_io.py", line 42, in read_dispatched
    return reader.read_elem(elem)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anndata/_io/utils.py", line 211, in func_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anndata/_io/specs/registry.py", line 275, in read_elem
    return self.callback(read_func, elem.name, elem, iospec=iospec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anndata/_io/h5ad.py", line 239, in callback
    **{
      ^
  File "/usr/local/lib/python3.11/site-packages/anndata/_io/h5ad.py", line 242, in <dictcomp>
    k: read_dispatched(elem[k], callback)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anndata/experimental/_dispatch_io.py", line 42, in read_dispatched
    return reader.read_elem(elem)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anndata/_io/utils.py", line 211, in func_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anndata/_io/specs/registry.py", line 275, in read_elem
    return self.callback(read_func, elem.name, elem, iospec=iospec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anndata/_io/h5ad.py", line 255, in callback
    return read_dataframe(elem)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anndata/_io/h5ad.py", line 317, in read_dataframe
    return read_elem(group)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anndata/_io/specs/registry.py", line 351, in read_elem
    return Reader(_REGISTRY).read_elem(elem)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anndata/_io/utils.py", line 211, in func_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anndata/_io/specs/registry.py", line 274, in read_elem
    return read_func(elem)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anndata/_io/specs/methods.py", line 841, in read_dataframe
    {k: _reader.read_elem(elem[k]) for k in columns},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anndata/_io/specs/methods.py", line 841, in <dictcomp>
    {k: _reader.read_elem(elem[k]) for k in columns},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anndata/_io/utils.py", line 211, in func_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anndata/_io/specs/registry.py", line 274, in read_elem
    return read_func(elem)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anndata/_io/specs/methods.py", line 952, in read_categorical
    categories=_reader.read_elem(elem["categories"]),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anndata/_io/utils.py", line 211, in func_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anndata/_io/specs/registry.py", line 272, in read_elem
    read_func = self.registry.get_read(type(elem), iospec, modifiers, reader=self)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anndata/_io/specs/registry.py", line 167, in get_read
    raise IORegistryError._from_read_parts(
anndata._io.specs.registry.IORegistryError: No read method registered for IOSpec(encoding_type='nullable-string-array', encoding_version='0.1.0') from <class 'h5py._hl.group.Group'>. You may need to update your installation of anndata.
Error raised while reading key 'categories' of <class 'h5py._hl.group.Group'> from /obs/sample
```


i also checked the h5ad file using h5py and basically found some differences:

working: `obs/_index: dtype=object, shape=(68526,), sample=b'AAACCCAGTGCCGAAA-1_2hpf_REP1_cellbender_filter'` and 
not working: ` obs/_index/values: dtype=object, shape=(68526,), sample=b'AAACCCAGTGCCGAAA-1_2hpf_REP1_cellbender_filter'`

**Comment by MaximilianLombardo** [comment]
Hi,

Different root cause from the original 2023 thread — your traceback exposes the real issue (the generic "File must be an .h5ad object" message is misleading; cellxgene's adaptor catches the underlying `IORegistryError` and re-raises it, which is why the older comments here ended up chasing Python versions):

```
IORegistryError: No read method registered for
IOSpec(encoding_type='nullable-string-array', encoding_version='0.1.0')
```

The `nullable-string-array` encoding was introduced in **anndata 0.11.0**. Your `.h5ad` was written with anndata ≥ 0.11, but the anndata installed in your cellxgene environment is older (0.10.x or earlier) and doesn't know how to read that encoding. The categorical column `obs/sample` in your file has nullable string categories, which triggers the new encoding path.

Two options:

1. **Upgrade anndata in the cellxgene environment:**
   ```
   pip install --upgrade "anndata>=0.11"
   ```
   cellxgene's requirement is `anndata>=0.8.0` with no upper bound (https://github.com/chanzuckerberg/cellxgene/blob/main/server/requirements.txt), and I just verified end-to-end that `cellxgene launch` works against a nullable-string-array h5ad with anndata 0.12.14 installed.

2. **Re-save the file with anndata, casting the offending columns to plain category:**
   ```python
   import anndata as ad
   adata = ad.read_h5ad("yourfile.h5ad")
   adata.obs["sample"] = adata.obs["sample"].astype(str).astype("category")
   adata.write_h5ad("yourfile_compat.h5ad")
   ```

Note that the standalone `cellxgene` desktop tool is in maintenance mode. For ongoing visualization work, https://cellxgene.cziscience.com (CZ CELLxGENE Discover) is the actively developed product.

**Comment by johannesnicolaus** [comment]
Hi, thank you so much for the answer. I tried the 1st option, but I now get error `zarr-python major version > 2 is not supported` when running cellxgene launch. The 2nd option seems to work well, so I'm going to go with this for now, thank you.
