### ISSUE TITLE
[BUG] Problems with latest AnnData version

### ISSUE THREAD

**Issue by const-ae** [chanzuckerberg/cellxgene#2706]
**Describe the bug**

Starting `cellxgene launch ~/datasets/precancer_atlas/sce_small.h5ad` with the latest version of AnnData (0.10.9) crashes because calling `data.obs.reset_index(inplace=TRUE)` (https://github.com/chanzuckerberg/cellxgene/blob/main/server/data_anndata/anndata_adaptor.py#L113) puts the object in to an inconsistent state.

When I install Anndata version 0.10.5 the problem disappears.

**Output**

```
/Users/ahlmanne/prog/experiments/cellxgene/.cellxgene/lib/python3.12/site-packages/server/data_anndata/anndata_adaptor.py:241: UserWarning: Anndata data matrix is in float64 format not float32. Precision may be truncated.
  warnings.warn(
WARNING:root:Type float64 will be converted to 32 bit float and may lose precision.
WARNING:root:Type float64 will be converted to 32 bit float and may lose precision.
WARNING:root:Type float64 will be converted to 32 bit float and may lose precision.
WARNING:root:Type float64 will be converted to 32 bit float and may lose precision.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ahlmanne/prog/experiments/cellxgene/.cellxgene/lib/python3.12/site-packages/server/data_anndata/anndata_adaptor.py", line 34, in __init__
    self._validate_and_initialize()
  File "/Users/ahlmanne/prog/experiments/cellxgene/.cellxgene/lib/python3.12/site-packages/server/data_anndata/anndata_adaptor.py", line 202, in _validate_and_initialize
    self._create_schema()
  File "/Users/ahlmanne/prog/experiments/cellxgene/.cellxgene/lib/python3.12/site-packages/server/data_anndata/anndata_adaptor.py", line 146, in _create_schema
    for layout in self.get_embedding_names():
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahlmanne/prog/experiments/cellxgene/.cellxgene/lib/python3.12/site-packages/server/data_anndata/anndata_adaptor.py", line 305, in get_embedding_names
    layouts = [key[2:] for key in self.data.obsm_keys() if type(key) is str and key.startswith("X_")]
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahlmanne/prog/experiments/cellxgene/.cellxgene/lib/python3.12/site-packages/anndata/_core/anndata.py", line 929, in obsm_keys
    return list(self.obsm.keys())
                ^^^^^^^^^
  File "/Users/ahlmanne/prog/experiments/cellxgene/.cellxgene/lib/python3.12/site-packages/anndata/_core/aligned_mapping.py", line 422, in __get__
    return self.construct(obj, store=getattr(obj, f"_{self.name}"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahlmanne/prog/experiments/cellxgene/.cellxgene/lib/python3.12/site-packages/anndata/_core/aligned_mapping.py", line 403, in construct
    return self.cls(obj, axis=self.axis, store=store)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahlmanne/prog/experiments/cellxgene/.cellxgene/lib/python3.12/site-packages/anndata/_core/aligned_mapping.py", line 297, in __init__
    super().__init__(parent, store=store)
  File "/Users/ahlmanne/prog/experiments/cellxgene/.cellxgene/lib/python3.12/site-packages/anndata/_core/aligned_mapping.py", line 210, in __init__
    self._data[k] = self._validate_value(v, k)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahlmanne/prog/experiments/cellxgene/.cellxgene/lib/python3.12/site-packages/anndata/_core/aligned_mapping.py", line 275, in _validate_value
    raise ValueError(msg) from None
ValueError: value.index does not match parent’s obs names:
Index are different

Attribute "inferred_type" are different
[left]:  string
[right]: integer
```

**Version (please complete the following information):**
 - Desktop: Macbook pro M3
 - Version: 1.3.0

**Comment by pcm32** [comment]
I was experiencing this as well using the bioconda container setup for cellxgene 1.3.0. I switched to conda where I had cellxgene 1.3.0 installed next to AnnData 0.11, however the bug appears with that version as well... maybe it is down to specific pandas versions?

These are the versions that conda installed (that still exhibit the issue with an AnnData generated in an AnnData 0.10.8 environment)
```
  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge 
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu 
  aniso8601          conda-forge/noarch::aniso8601-9.0.1-pyhd8ed1ab_0 
  anndata            conda-forge/noarch::anndata-0.11.0-pyhd8ed1ab_0 
  array-api-compat   conda-forge/noarch::array-api-compat-1.9.1-pyhd8ed1ab_0 
  aws-c-auth         conda-forge/linux-64::aws-c-auth-0.8.0-h7205bc0_5 
  aws-c-cal          conda-forge/linux-64::aws-c-cal-0.8.0-he70792b_1 
  aws-c-common       conda-forge/linux-64::aws-c-common-0.10.0-hb9d3cd8_0 
  aws-c-compression  conda-forge/linux-64::aws-c-compression-0.3.0-hba2fe39_1 
  aws-c-event-stream conda-forge/linux-64::aws-c-event-stream-0.5.0-h18ad228_3 
  aws-c-http         conda-forge/linux-64::aws-c-http-0.9.0-hc1812d8_4 
  aws-c-io           conda-forge/linux-64::aws-c-io-0.15.0-h9a7ba4f_3 
  aws-c-mqtt         conda-forge/linux-64::aws-c-mqtt-0.11.0-h7f264a7_4 
  aws-c-s3           conda-forge/linux-64::aws-c-s3-0.7.0-hdd898f0_6 
  aws-c-sdkutils     conda-forge/linux-64::aws-c-sdkutils-0.2.0-hba2fe39_1 
  aws-checksums      conda-forge/linux-64::aws-checksums-0.2.0-hba2fe39_1 
  aws-crt-cpp        conda-forge/linux-64::aws-crt-cpp-0.29.1-hd83ed67_1 
  aws-sdk-cpp        conda-forge/linux-64::aws-sdk-cpp-1.11.407-h4a57546_8 
  azure-core-cpp     conda-forge/linux-64::azure-core-cpp-1.14.0-h5cfcd09_0 
  azure-identity-cpp conda-forge/linux-64::azure-identity-cpp-1.10.0-h113e628_0 
  azure-storage-blo~ conda-forge/linux-64::azure-storage-blobs-cpp-12.13.0-h3cf044e_1 
  azure-storage-com~ conda-forge/linux-64::azure-storage-common-cpp-12.8.0-h736e048_1 
  blinker            conda-forge/noarch::blinker-1.8.2-pyhd8ed1ab_0 
  boto3              conda-forge/noarch::boto3-1.35.55-pyh0610db2_0 
  botocore           conda-forge/noarch::botocore-1.35.56-pyge310_1234567_0 
  brotli-python      conda-forge/linux-64::brotli-python-1.1.0-py311hfdbb021_2 
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h4bc722e_7 
  c-ares             conda-forge/linux-64::c-ares-1.34.2-heb4867d_0 
  ca-certificates    conda-forge/linux-64::ca-certificates-2024.8.30-hbcca054_0 
  cached-property    conda-forge/noarch::cached-property-1.5.2-hd8ed1ab_1 
  cached_property    conda-forge/noarch::cached_property-1.5.2-pyha770c72_1 
  cellxgene          bioconda/noarch::cellxgene-1.3.0-pyhdfd78af_0 
  certifi            conda-forge/noarch::certifi-2024.8.30-pyhd8ed1ab_0 
  cffi               conda-forge/linux-64::cffi-1.17.1-py311hf29c0ef_0 
  charset-normalizer conda-forge/noarch::charset-normalizer-3.4.0-pyhd8ed1ab_0 
  click              conda-forge/noarch::click-8.1.7-unix_pyh707e725_0 
  exceptiongroup     conda-forge/noarch::exceptiongroup-1.2.2-pyhd8ed1ab_0 
  fastobo            bioconda/linux-64::fastobo-0.12.3-py311ha86b268_2 
  flask              conda-forge/noarch::flask-3.0.3-pyhd8ed1ab_0 
  flask-compress     conda-forge/noarch::flask-compress-1.17-pyhd8ed1ab_0 
  flask-cors         conda-forge/noarch::flask-cors-5.0.0-pyhd8ed1ab_0 
  flask-restful      conda-forge/noarch::flask-restful-0.3.10-pyhd8ed1ab_0 
  flask-server-timi~ conda-forge/noarch::flask-server-timing-0.1.2-pyh9f0ad1d_0 
  flask-talisman     conda-forge/noarch::flask-talisman-1.1.0-pyhd8ed1ab_0 
  flatten-dict       conda-forge/noarch::flatten-dict-0.4.2-pyhd8ed1ab_1 
  fmt                conda-forge/linux-64::fmt-11.0.2-h434a139_0 
  fsspec             conda-forge/noarch::fsspec-0.7.4-py_0 
  greenlet           conda-forge/linux-64::greenlet-3.1.1-py311hfdbb021_0 
  gunicorn           conda-forge/linux-64::gunicorn-23.0.0-py311h38be061_1 
  h2                 conda-forge/noarch::h2-4.1.0-pyhd8ed1ab_0 
  h5py               conda-forge/linux-64::h5py-3.12.1-nompi_py311hb639ac4_102 
  hdf5               conda-forge/linux-64::hdf5-1.14.3-nompi_hdf9ad27_105 
  hpack              conda-forge/noarch::hpack-4.0.0-pyh9f0ad1d_0 
  hyperframe         conda-forge/noarch::hyperframe-6.0.1-pyhd8ed1ab_0 
  idna               conda-forge/noarch::idna-3.10-pyhd8ed1ab_0 
  importlib-metadata conda-forge/noarch::importlib-metadata-8.5.0-pyha770c72_0 
  itsdangerous       conda-forge/noarch::itsdangerous-2.2.0-pyhd8ed1ab_0 
  jinja2             conda-forge/noarch::jinja2-3.1.4-pyhd8ed1ab_0 
  jmespath           conda-forge/noarch::jmespath-1.0.1-pyhd8ed1ab_0 
  kernel-headers_li~ conda-forge/noarch::kernel-headers_linux-64-3.10.0-he073ed8_18 
  keyutils           conda-forge/linux-64::keyutils-1.6.1-h166bdaf_0 
  krb5               conda-forge/linux-64::krb5-1.21.3-h659f571_0 
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.43-h712a8e2_2 
  libabseil          conda-forge/linux-64::libabseil-20240722.0-cxx17_h5888daf_1 
  libaec             conda-forge/linux-64::libaec-1.1.3-h59595ed_0 
  libblas            conda-forge/linux-64::libblas-3.9.0-25_linux64_openblas 
  libcblas           conda-forge/linux-64::libcblas-3.9.0-25_linux64_openblas 
  libcrc32c          conda-forge/linux-64::libcrc32c-1.1.2-h9c3ff4c_0 
  libcurl            conda-forge/linux-64::libcurl-8.10.1-hbbe4b11_0 
  libedit            conda-forge/linux-64::libedit-3.1.20191231-he28a2e2_2 
  libev              conda-forge/linux-64::libev-4.33-hd590300_2 
  libexpat           conda-forge/linux-64::libexpat-2.6.4-h5888daf_0 
  libffi             conda-forge/linux-64::libffi-3.4.2-h7f98852_5 
  libgcc             conda-forge/linux-64::libgcc-14.2.0-h77fa898_1 
  libgcc-ng          conda-forge/linux-64::libgcc-ng-14.2.0-h69a702a_1 
  libgfortran        conda-forge/linux-64::libgfortran-14.2.0-h69a702a_1 
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-14.2.0-h69a702a_1 
  libgfortran5       conda-forge/linux-64::libgfortran5-14.2.0-hd5240d6_1 
  libgomp            conda-forge/linux-64::libgomp-14.2.0-h77fa898_1 
  libgoogle-cloud    conda-forge/linux-64::libgoogle-cloud-2.30.0-h804f50b_1 
  libgoogle-cloud-s~ conda-forge/linux-64::libgoogle-cloud-storage-2.30.0-h0121fbd_1 
  libgrpc            conda-forge/linux-64::libgrpc-1.67.1-hc2c308b_0 
  libiconv           conda-forge/linux-64::libiconv-1.17-hd590300_2 
  liblapack          conda-forge/linux-64::liblapack-3.9.0-25_linux64_openblas 
  libllvm14          conda-forge/linux-64::libllvm14-14.0.6-hcd5def8_4 
  libnghttp2         conda-forge/linux-64::libnghttp2-1.64.0-h161d5f1_0 
  libnsl             conda-forge/linux-64::libnsl-2.0.1-hd590300_0 
  libopenblas        conda-forge/linux-64::libopenblas-0.3.28-pthreads_h94d23a6_1 
  libprotobuf        conda-forge/linux-64::libprotobuf-5.28.2-h5b01275_0 
  libre2-11          conda-forge/linux-64::libre2-11-2024.07.02-hbbce691_1 
  libsqlite          conda-forge/linux-64::libsqlite-3.47.0-hadc24fc_1 
  libssh2            conda-forge/linux-64::libssh2-1.11.0-h0841786_0 
  libstdcxx          conda-forge/linux-64::libstdcxx-14.2.0-hc0a3c3a_1 
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-14.2.0-h4852527_1 
  libuuid            conda-forge/linux-64::libuuid-2.38.1-h0b41bf4_0 
  libwebp-base       conda-forge/linux-64::libwebp-base-1.4.0-hd590300_0 
  libxcrypt          conda-forge/linux-64::libxcrypt-4.4.36-hd590300_1 
  libxml2            conda-forge/linux-64::libxml2-2.13.4-h064dc61_2 
  libzlib            conda-forge/linux-64::libzlib-1.3.1-hb9d3cd8_2 
  llvmlite           conda-forge/linux-64::llvmlite-0.43.0-py311h9c9ff8c_1 
  lz4-c              conda-forge/linux-64::lz4-c-1.9.4-hcb278e6_0 
  markupsafe         conda-forge/linux-64::markupsafe-3.0.2-py311h2dc5d0c_0 
  natsort            conda-forge/noarch::natsort-8.4.0-pyhd8ed1ab_0 
  ncurses            conda-forge/linux-64::ncurses-6.5-he02047a_1 
  numba              conda-forge/linux-64::numba-0.60.0-py311h4bc866e_0 
  numpy              conda-forge/linux-64::numpy-2.0.2-py311h71ddf71_0 
  openssl            conda-forge/linux-64::openssl-3.3.2-hb9d3cd8_0 
  packaging          conda-forge/noarch::packaging-24.1-pyhd8ed1ab_0 
  pandas             conda-forge/linux-64::pandas-2.2.2-py311h14de704_1 
  pathlib2           conda-forge/linux-64::pathlib2-2.3.7.post1-py311h38be061_4 
  pip                conda-forge/noarch::pip-24.3.1-pyh8b19718_0 
  pycparser          conda-forge/noarch::pycparser-2.22-pyhd8ed1ab_0 
  pysocks            conda-forge/noarch::pysocks-1.7.1-pyha2e5f31_6 
  python             conda-forge/linux-64::python-3.11.10-hc5c86c4_3_cpython 
  python-dateutil    conda-forge/noarch::python-dateutil-2.9.0-pyhd8ed1ab_0 
  python-flatbuffers conda-forge/noarch::python-flatbuffers-1.12-pyhd8ed1ab_1 
  python-tzdata      conda-forge/noarch::python-tzdata-2024.2-pyhd8ed1ab_0 
  python_abi         conda-forge/linux-64::python_abi-3.11-5_cp311 
  pytz               conda-forge/noarch::pytz-2024.2-pyhd8ed1ab_0 
  pyyaml             conda-forge/linux-64::pyyaml-6.0.2-py311h9ecbd09_1 
  re2                conda-forge/linux-64::re2-2024.07.02-h77b4e00_1 
  readline           conda-forge/linux-64::readline-8.2-h8228510_1 
  requests           conda-forge/noarch::requests-2.32.3-pyhd8ed1ab_0 
  s2n                conda-forge/linux-64::s2n-1.5.6-h0e56266_0 
  s3fs               conda-forge/noarch::s3fs-0.4.2-py_0 
  s3transfer         conda-forge/noarch::s3transfer-0.10.3-pyhd8ed1ab_0 
  scipy              conda-forge/linux-64::scipy-1.14.1-py311he9a78e4_1 
  setuptools         conda-forge/noarch::setuptools-75.3.0-pyhd8ed1ab_0 
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0 
  spdlog             conda-forge/linux-64::spdlog-1.14.1-hed91bc2_1 
  sqlalchemy         conda-forge/linux-64::sqlalchemy-2.0.36-py311h9ecbd09_0 
  sysroot_linux-64   conda-forge/noarch::sysroot_linux-64-2.17-h4a8ded7_18 
  tiledb             conda-forge/linux-64::tiledb-2.26.2-h7560d31_5 
  tiledb-py          conda-forge/linux-64::tiledb-py-0.32.5-py311h9fa59f9_0 
  tk                 conda-forge/linux-64::tk-8.6.13-noxft_h4845f30_101 
  typing-extensions  conda-forge/noarch::typing-extensions-4.12.2-hd8ed1ab_0 
  typing_extensions  conda-forge/noarch::typing_extensions-4.12.2-pyha770c72_0 
  tzdata             conda-forge/noarch::tzdata-2024b-hc8b5060_0 
  urllib3            conda-forge/noarch::urllib3-2.2.3-pyhd8ed1ab_0 
  werkzeug           conda-forge/noarch::werkzeug-3.1.2-pyhd8ed1ab_0 
  wheel              conda-forge/noarch::wheel-0.44.0-pyhd8ed1ab_0 
  xz                 conda-forge/linux-64::xz-5.2.6-h166bdaf_0 
  yaml               conda-forge/linux-64::yaml-0.2.5-h7f98852_2 
  zipp               conda-forge/noarch::zipp-3.20.2-pyhd8ed1ab_0 
  zstandard          conda-forge/linux-64::zstandard-0.23.0-py311hbc35293_1 
  zstd               conda-forge/linux-64::zstd-1.5.6-ha6fb4c9_0 
```

I then downgraded to AnnData 0.10.8 and it worked...

**Comment by const-ae** [comment]
No, sorry, I did not do the preprocessing with scVI.

**Comment by dimalvovs** [comment]
this is old, but in case still useful for someone: for me the problem was that the `h5ad` I had was converted from a `Seurat` object and had missing attrs: 
```
encoding_dict = {'encoding-type': 'anndata', 'encoding-version': '0.1.0'}

with h5py.File('scAtlas.rds.h5ad', "a") as f:
    for key, value in encoding_dict.items():
        f.attrs[key] = value
```

**Comment by colinmegill** [comment]
Awesome thanks for submitting :)
