### ISSUE TITLE
Need better CLI UX when common errors occur

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#331]
Our CLI UX needs to generate better errors when common failures occur.   For example, when the CLI can't find the input h5ad file, it currently generates a stack crawl which obscures the real issue (missing file), and makes it look like some sort of major error or bug is manifest.

```
# cellxgene --title 'foo' scanpy ../scanpy-datasets/10x\ 1.3MM\ mouse/
/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/bin/cellxgene", line 11, in <module>
    load_entry_point('cellxgene', 'console_scripts', 'cellxgene')()
  File "/mnt/c/Users/bruce/projects/cellxgene/server/app/app.py", line 88, in main
    args.func(args)
  File "/mnt/c/Users/bruce/projects/cellxgene/server/app/app.py", line 59, in run_scanpy
    app.data = ScanpyEngine(args.data_directory, layout_method=args.layout, diffexp_method=args.diffexp)
  File "/mnt/c/Users/bruce/projects/cellxgene/server/app/scanpy_engine/scanpy_engine.py", line 27, in __init__
    super().__init__(data, layout_method=layout_method, diffexp_method=diffexp_method)
  File "/mnt/c/Users/bruce/projects/cellxgene/server/app/driver/driver.py", line 16, in __init__
    self.data = self._load_data(data)
  File "/mnt/c/Users/bruce/projects/cellxgene/server/app/scanpy_engine/scanpy_engine.py", line 81, in _load_data
    return sc.read(os.path.join(data, "data.h5ad"))
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/scanpy/readwrite.py", line 75, in read
    backup_url=backup_url, cache=cache, **kwargs)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/scanpy/readwrite.py", line 276, in _read
    return read_h5ad(filename, backed=backed)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/anndata/readwrite/read.py", line 412, in read_h5ad
    d = _read_h5ad(filename=filename)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/anndata/readwrite/read.py", line 438, in _read_h5ad
    f = h5py.File(filename, 'r')
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/anndata/h5py/h5sparse.py", line 141, in __init__
    **kwds,
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '../scanpy-datasets/10x 1.3MM mouse/data.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

**Comment by neuromusic** [comment]
current behavior:

```
(cellxgene-dev) czirwc1osx1002:prime_genes justinkiggins$ cellxgene launch hello.h5ad
Usage: cellxgene launch [OPTIONS] <data file>
Try "cellxgene launch --help" for help.

Error: Invalid value for "<data file>": File "hello.h5ad" does not exist.
```

closing this issue & we can reopen if there are specific examples errors that need cleaner feedback to the user
