### ISSUE TITLE
pbmc3k test data set fails diffexp calculation

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#347]
Load the latest pbmc3k "prepared" data set, ask for diffexp calculation from the f/e, and you get back bogus JSON from the CLI (contains NaN's which are not legal in JSON).

This looks like a bug in the diffexp CLI calculation.

```
[
  [
    22, 
    0.0, 
    NaN, 
    NaN, 
    -0.03223249316215515, 
    -0.03223249316215515
  ], 
  [
    59, 
    3.725290298461914e-09, 
    1.5152738737504437e-91, 
    0.0, 
    -0.03832865506410599, 
    -0.038328658789396286
  ], 
  [
    79, 
    2.177830457687378, 
    2.1666501748703266e-165, 
    0.0, 
    1.6735427379608154, 
    -0.5042877197265625
  ], 
  [
    242, 
    3.2382142543792725, 
    3.0608739607110622e-263, 
    0.0, 
    2.9571640491485596, 
    -0.2810501456260681
  ], 
  [
    283, 
    2.637721061706543, 
    1.900322634622438e-299, 
    0.0, 
    2.224553108215332, 
    -0.41316789388656616
  ], 
  [
    523, 
    2.9486725330352783, 
    5.912974536818484e-257, 
    0.0, 
    2.600834846496582, 
    -0.3478377163410187
  ], 
  [
    666, 
    2.5547847747802734, 
    2.679752079590864e-155, 
    0.0, 
    2.289745807647705, 
    -0.26503893733024597
  ], 
  [
    701, 
    0.0, 
    NaN, 
    NaN, 
    -0.0792982429265976, 
    -0.0792982429265976
  ], 
  [
    802, 
    2.4982500076293945, 
    1.1483218184552997e-120, 
    0.0, 
    2.3370797634124756, 
    -0.16117022931575775
  ], 
  [
    884, 
    2.120547294616699, 
    2.907435060589997e-184, 
    0.0, 
    1.6300982236862183, 
    -0.4904491603374481
  ]
]
```

**Comment by bkmartinjr** [comment]
More info - the CLI stdout/stderr contains:

```
# cellxgene scanpy ../cellxgene-datasets/cellxgene-prepare/pbmc3
k/
/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
 * Running on http://127.0.0.1:5005/ (Press CTRL+C to quit)
 * Restarting with stat
/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
 * Debugger is active!
 * Debugger PIN: 188-773-702
127.0.0.1 - - [18/Oct/2018 09:58:15] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Oct/2018 09:58:23] "GET /static/js/main.b5db1c3a.js.map HTTP/1.1" 200 -
127.0.0.1 - - [18/Oct/2018 09:58:23] "OPTIONS /api/v0.2/config HTTP/1.1" 200 -
127.0.0.1 - - [18/Oct/2018 09:58:23] "OPTIONS /api/v0.2/schema HTTP/1.1" 200 -
127.0.0.1 - - [18/Oct/2018 09:58:23] "OPTIONS /api/v0.2/annotations/obs HTTP/1.1" 200 -
127.0.0.1 - - [18/Oct/2018 09:58:23] "OPTIONS /api/v0.2/annotations/var HTTP/1.1" 200 -
127.0.0.1 - - [18/Oct/2018 09:58:23] "OPTIONS /api/v0.2/layout/obs HTTP/1.1" 200 -
127.0.0.1 - - [18/Oct/2018 09:58:23] "GET /api/v0.2/config HTTP/1.1" 200 -
127.0.0.1 - - [18/Oct/2018 09:58:23] "GET /api/v0.2/schema HTTP/1.1" 200 -
127.0.0.1 - - [18/Oct/2018 09:58:23] "GET /api/v0.2/annotations/obs HTTP/1.1" 200 -
127.0.0.1 - - [18/Oct/2018 09:58:23] "GET /api/v0.2/annotations/var HTTP/1.1" 200 -
127.0.0.1 - - [18/Oct/2018 09:58:23] "GET /api/v0.2/layout/obs HTTP/1.1" 200 -
127.0.0.1 - - [18/Oct/2018 09:58:49] "OPTIONS /api/v0.2/diffexp/obs HTTP/1.1" 200 -
/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
127.0.0.1 - - [18/Oct/2018 09:58:49] "POST /api/v0.2/diffexp/obs HTTP/1.1" 200 -
```

**Comment by csweaver** [comment]
This is expected based on what Alex said. Scipy's stats package does not play well with sparse matrices. #348 should fix this problem. Should I file a separate bug to handle NaNs in our JSON parser?

**Comment by bkmartinjr** [comment]
@freeman-lab said this data set is dense (although he didn't sound 100% certain).

**Comment by bkmartinjr** [comment]
Re: legal JSON - we definitely need the b/e to always generate legal JSON.   Splitting the issue is fine w/ me.

**Comment by bkmartinjr** [comment]
I see a similar error on the immune_bone_marrow data set:

```
127.0.0.1 - - [18/Oct/2018 12:38:46] "OPTIONS /api/v0.2/diffexp/obs HTTP/1.1" 200 -
/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/scipy/stats/stats.py:245: RuntimeWarning: The input array could not be properly checked for nan values. nan values will be ignored.
  "values. nan values will be ignored.", RuntimeWarning)
/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3194: RuntimeWarning: Degrees of freedom <= 0 for slice
  **kwargs)
127.0.0.1 - - [18/Oct/2018 12:39:02] "POST /api/v0.2/diffexp/obs HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/flask_restful_swagger_2/__init__.py", line 39, in decorator
    return f(*args, **kwargs)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/flask_restful_swagger_2/swagger.py", line 219, in inner
    return f(self, *args, **kwargs)
  File "/mnt/c/Users/bruce/projects/cellxgene/server/app/rest_api/rest.py", line 608, in post
    return make_response(e.message, HTTPStatus.BAD_REQUEST)
AttributeError: 'ValueError' object has no attribute 'message'
```

**Comment by bkmartinjr** [comment]
One more note: we have the same data set prepared in two different ways (Jeremy's script and direct from Alex saved as `example-dataset` in the repo).  The former errors out, the latter does not.

**Comment by csweaver** [comment]
Do you have the json input to the rest call that give the NaNs? I need a test case.

**Comment by bkmartinjr** [comment]
It failed reliably on any subset (selection), so I didn't bother.  I suspect if you just compare two random sets (eg, [0-100], [200-300]) it will choke

**Comment by bkmartinjr** [comment]
FYI, the issue with the immune_bone_marrow dataset was slightly different - we were not properly handling sparse formats.   I'll fix that.  At which point, the error looks exactly like the one we see with the dense pbmc3k dataset.
