### ISSUE TITLE
igraph library missing when running `cellxgene prepare`

### ISSUE THREAD

**Issue by csweaver** [chanzuckerberg/cellxgene#415]
It looks like the igraph librarary wasn't installed by default when installing scanpy. pip installing igraph still gives and error that I should be using jgraph... 

I think we need to add this to our own requirments.txt file, but I haven't been sucessful in running it yet

```
(venv) ✔ ~/Documents/Git/cellxgene [csweaver/validation|CHERRY-PICKING|…1⚑ 41] 
15:07 $ cellxgene prepare paul15.h5ad 
[cellxgene] Starting CLI...
[cellxgene] Loading data from paul15.h5ad, please wait...
[cellxgene] Beginning preprocessing...
[cellxgene] Progress  [##############################------]   83%  Calculating clusters               
Traceback (most recent call last):
  File "/Users/charlotteweaver/Documents/Git/cellxgene/venv/bin/cellxgene", line 11, in <module>
    load_entry_point('cellxgene', 'console_scripts', 'cellxgene')()
  File "/Users/charlotteweaver/Documents/Git/cellxgene/venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/charlotteweaver/Documents/Git/cellxgene/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/charlotteweaver/Documents/Git/cellxgene/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/charlotteweaver/Documents/Git/cellxgene/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/charlotteweaver/Documents/Git/cellxgene/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/charlotteweaver/Documents/Git/cellxgene/server/cli/prepare.py", line 153, in prepare
    step(adata)
  File "/Users/charlotteweaver/Documents/Git/cellxgene/server/cli/prepare.py", line 115, in run_louvain
    sc.tl.louvain(adata)
  File "/Users/charlotteweaver/Documents/Git/cellxgene/venv/lib/python3.6/site-packages/scanpy/tools/louvain.py", line 103, in louvain
    g = utils.get_igraph_from_adjacency(adjacency, directed=directed)
  File "/Users/charlotteweaver/Documents/Git/cellxgene/venv/lib/python3.6/site-packages/scanpy/utils.py", line 304, in get_igraph_from_adjacency
    import igraph as ig
ModuleNotFoundError: No module named 'igraph'
(venv) ✘-1 ~/Documents/Git/cellxgene [csweaver/validation|CHERRY-PICKING|…1⚑ 41] 
15:07 $ pip install igraph
Collecting igraph
  Downloading https://files.pythonhosted.org/packages/91/15/7c606c483a401dfdcdd19f2688c83585ee3b5ef401bd4e0e647660ef5b3f/igraph-0.1.11-py2.py3-none-any.whl (119kB)
    100% |████████████████████████████████| 122kB 2.5MB/s 
Collecting ipython (from igraph)
  Downloading https://files.pythonhosted.org/packages/1b/e2/ffb8c1b574f972cf4183b0aac8f16b57f1e3bbe876b31555b107ea3fd009/ipython-7.1.1-py3-none-any.whl (764kB)
    100% |████████████████████████████████| 768kB 1.6MB/s 
Requirement already satisfied: setuptools>=18.5 in ./venv/lib/python3.6/site-packages (from ipython->igraph)
Collecting pexpect; sys_platform != "win32" (from ipython->igraph)
  Using cached https://files.pythonhosted.org/packages/89/e6/b5a1de8b0cc4e07ca1b305a4fcc3f9806025c1b651ea302646341222f88b/pexpect-4.6.0-py2.py3-none-any.whl
Collecting traitlets>=4.2 (from ipython->igraph)
  Using cached https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl
Collecting pygments (from ipython->igraph)
  Using cached https://files.pythonhosted.org/packages/02/ee/b6e02dc6529e82b75bb06823ff7d005b141037cb1416b10c6f00fc419dca/Pygments-2.2.0-py2.py3-none-any.whl
Collecting backcall (from ipython->igraph)
Collecting appnope; sys_platform == "darwin" (from ipython->igraph)
  Using cached https://files.pythonhosted.org/packages/87/a9/7985e6a53402f294c8f0e8eff3151a83f1fb901fa92909bb3ff29b4d22af/appnope-0.1.0-py2.py3-none-any.whl
Collecting prompt-toolkit<2.1.0,>=2.0.0 (from ipython->igraph)
  Downloading https://files.pythonhosted.org/packages/d1/e6/adb3be5576f5d27c6faa33f1e9fea8fe5dbd9351db12148de948507e352c/prompt_toolkit-2.0.7-py3-none-any.whl (338kB)
    100% |████████████████████████████████| 348kB 2.8MB/s 
Collecting pickleshare (from ipython->igraph)
  Using cached https://files.pythonhosted.org/packages/9a/41/220f49aaea88bc6fa6cba8d05ecf24676326156c23b991e80b3f2fc24c77/pickleshare-0.7.5-py2.py3-none-any.whl
Collecting jedi>=0.10 (from ipython->igraph)
  Using cached https://files.pythonhosted.org/packages/7a/1a/9bd24a185873b998611c2d8d4fb15cd5e8a879ead36355df7ee53e9111bf/jedi-0.13.1-py2.py3-none-any.whl
Requirement already satisfied: decorator in ./venv/lib/python3.6/site-packages (from ipython->igraph)
Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython->igraph)
  Using cached https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl
Requirement already satisfied: six in ./venv/lib/python3.6/site-packages (from traitlets>=4.2->ipython->igraph)
Collecting ipython-genutils (from traitlets>=4.2->ipython->igraph)
  Using cached https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit<2.1.0,>=2.0.0->ipython->igraph)
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting parso>=0.3.0 (from jedi>=0.10->ipython->igraph)
  Using cached https://files.pythonhosted.org/packages/09/51/9c48a46334be50c13d25a3afe55fa05c445699304c5ad32619de953a2305/parso-0.3.1-py2.py3-none-any.whl
Installing collected packages: ptyprocess, pexpect, ipython-genutils, traitlets, pygments, backcall, appnope, wcwidth, prompt-toolkit, pickleshare, parso, jedi, ipython, igraph
Successfully installed appnope-0.1.0 backcall-0.1.0 igraph-0.1.11 ipython-7.1.1 ipython-genutils-0.2.0 jedi-0.13.1 parso-0.3.1 pexpect-4.6.0 pickleshare-0.7.5 prompt-toolkit-2.0.7 ptyprocess-0.6.0 pygments-2.2.0 traitlets-4.3.2 wcwidth-0.1.7
You are using pip version 9.0.3, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(venv) ✔ ~/Documents/Git/cellxgene [csweaver/validation|CHERRY-PICKING|…1⚑ 41] 
15:07 $ cellxgene prepare paul15.h5ad 
[cellxgene] Starting CLI...
[cellxgene] Loading data from paul15.h5ad, please wait...
[cellxgene] Beginning preprocessing...
[cellxgene] Progress  [##############################------]   83%  Calculating clusters               
Traceback (most recent call last):
  File "/Users/charlotteweaver/Documents/Git/cellxgene/venv/bin/cellxgene", line 11, in <module>
    load_entry_point('cellxgene', 'console_scripts', 'cellxgene')()
  File "/Users/charlotteweaver/Documents/Git/cellxgene/venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/charlotteweaver/Documents/Git/cellxgene/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/charlotteweaver/Documents/Git/cellxgene/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/charlotteweaver/Documents/Git/cellxgene/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/charlotteweaver/Documents/Git/cellxgene/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/charlotteweaver/Documents/Git/cellxgene/server/cli/prepare.py", line 153, in prepare
    step(adata)
  File "/Users/charlotteweaver/Documents/Git/cellxgene/server/cli/prepare.py", line 115, in run_louvain
    sc.tl.louvain(adata)
  File "/Users/charlotteweaver/Documents/Git/cellxgene/venv/lib/python3.6/site-packages/scanpy/tools/louvain.py", line 103, in louvain
    g = utils.get_igraph_from_adjacency(adjacency, directed=directed)
  File "/Users/charlotteweaver/Documents/Git/cellxgene/venv/lib/python3.6/site-packages/scanpy/utils.py", line 304, in get_igraph_from_adjacency
    import igraph as ig
  File "/Users/charlotteweaver/Documents/Git/cellxgene/venv/lib/python3.6/site-packages/igraph/__init__.py", line 8, in <module>
    raise DeprecationWarning("To avoid name collision with the igraph project, "
DeprecationWarning: To avoid name collision with the igraph project, this visualization library has been renamed to 'jgraph'. Please upgrade when convenient.

```

**Comment by csweaver** [comment]
Update: `pip install jgraph` did not fix the issue.

@freeman-lab can you do a `pip freeze` of your cellxgene environment?

**Comment by bkmartinjr** [comment]
@freeman-lab - what is the status of this bug.  Please update or close if no longer an issue.

**Comment by bkmartinjr** [comment]
Closing due to lack of information.  Feel free to re-open if still an issue.  TY!

**Comment by prete** [comment]
Not to be re-opened but just in case somebody runs into the same problem. Fixed it by doing:
```
sudo apt-get install build-essential python-dev
pip install python-igraph
```

**Comment by bkmartinjr** [comment]
I will add this to the docs overhaul slated for our next release.  Thank you!
