### ISSUE TITLE
CLI bug in 0.9.0

### ISSUE THREAD

**Issue by falexwolf** [chanzuckerberg/cellxgene#748]
Only since updating to 0.9.0 (works in 0.8.0), I find:
```
$ cellxgene launch ~/data/burl18_gene_symbols.h5ad --open
Traceback (most recent call last):
  File "/Users/alexwolf/miniconda3/bin/cellxgene", line 7, in <module>
    from server.cli.cli import cli
  File "/Users/alexwolf/miniconda3/lib/python3.6/site-packages/server/cli/cli.py", line 3, in <module>
    from .launch import launch
  File "/Users/alexwolf/miniconda3/lib/python3.6/site-packages/server/cli/launch.py", line 13, in <module>
    from server.utils.constants import MODES
ModuleNotFoundError: No module named 'server.utils'
```

**Comment by hejing3283** [comment]
I ran into the same error
